### PR TITLE
Fixed parsing of pre-defined `$-?` global variables.

### LINKED ISSUE #1318: Bad gvar name: "$-0\n "
Blocks Opal from being able to run `rubyspec/language/predefined_spec.rb`
```
$ bundle exec rake mspec_rubyspec_nodejs PATTERN=spec/rubyspec/language/predefined_spec.rb

...

/Users/vais/opal/lib/opal/parser/lexer.rb:1189:in `yylex': An error occurred while compiling: rubyspec/language/predefined_spec (RuntimeError)

Bad gvar name: "$-0\n "
Source: rubyspec/language/predefined_spec:535:24
    @dollar_dash_zero = $-0
~~~~~~~~~~~~~~~~~~~~~~~^
	from /Users/vais/opal/lib/opal/parser/lexer.rb:84:in `next_token'
	from /Users/vais/opal/lib/opal/parser.rb:61:in `next_token'
	from /Users/vais/.rbenv/versions/2.2.3/lib/ruby/2.2.0/racc/parser.rb:258:in `_racc_do_parse_c'
	from /Users/vais/.rbenv/versions/2.2.3/lib/ruby/2.2.0/racc/parser.rb:258:in `do_parse'
	from /Users/vais/opal/lib/opal/parser.rb:54:in `parse_to_sexp'
	from /Users/vais/opal/lib/opal/parser.rb:39:in `parse'
	from /Users/vais/opal/lib/opal/compiler.rb:149:in `compile'
	from /Users/vais/opal/lib/opal/builder_processors.rb:91:in `compiled'
	from /Users/vais/opal/lib/opal/builder_processors.rb:101:in `requires'
	from /Users/vais/opal/lib/opal/builder.rb:139:in `process_require'
	from /Users/vais/opal/lib/opal/builder.rb:42:in `block in build_str'
	from /Users/vais/opal/lib/opal/builder.rb:42:in `map'
	from /Users/vais/opal/lib/opal/builder.rb:42:in `build_str'
	from /Users/vais/opal/lib/opal/cli.rb:111:in `block in build'
	from /Users/vais/opal/lib/opal/cli.rb:159:in `evals_or_file'
	from /Users/vais/opal/lib/opal/cli.rb:110:in `build'
	from /Users/vais/opal/lib/opal/cli.rb:121:in `compiled_source'
	from /Users/vais/opal/lib/opal/cli.rb:85:in `run_code'
	from /Users/vais/opal/lib/opal/cli.rb:71:in `run'
	from bin/opal:22:in `<main>'
```

### PR DESCRIPTION
**Pull request by iliabylich**
Closes #1318

### CODE REVIEW

**Comment by elia** [comment]
Is there any ruby spec that can be added?

**Comment by iliabylich** [comment]
@elia Opal now can parse `ruby/language/predefined_spec.rb` which contains specs for these constants, but generated JS is broken, mspec throws an error while running it. (Some specs are green btw :smile: )

**Comment by elia** [comment]
Great to hear!

**Comment by vais** [comment]
@iliabylich great work!

> Opal now can parse ruby/language/predefined_spec.rb which contains specs for these constants, but generated JS is broken, mspec throws an error while running it.

Can you please open another issue to document what's the next thing that is blocking `ruby/language/predefined_spec.rb`

**Comment by iliabylich** [comment]
Hold on, don't merge this yet please. Found one undocumented (I guess) global variable that was defined on the bottom of `predefined_spec.rb`

**Comment by iliabylich** [comment]
Alright, MRI supports all possible variables like `$-[\w\d]`, updated PR + specs, ready for merging I guess

**Comment by iliabylich** [comment]
@vais Take a look at this lines:
1. https://github.com/opal/opal/blob/master/opal/corelib/io.rb#L34
2. https://github.com/ruby/spec/blob/master/language/predefined_spec.rb#L633

MSpec internally uses IO for writing its report. Ruby/spec unintentionally breaks `$,` constant. As a result Opal tries to join an array of strings using this `Object.new` as a separator. MRI doc says that it's a correct behavior of `IO.print`, so I'll open an issue in ruby/spec and link it with an opal issue. `$,` definitely  should be restored to `nil` after this spec.

**Comment by vais** [comment]
@iliabylich interesting find... I wonder why this does not break for other Ruby implementations? By all means open an issue. cc @eregon

**Comment by eregon** [comment]
I believe it does not break on other impls because the assignment is not performed and the error is thrown instead :wink: (gvars have special setters)

**Comment by elia** [comment]
@iliabylich updated ruby spec on master :+1:

**Comment by iliabylich** [comment]
@elia Rebased to the latest master, added `ruby/language/predefined_spec.rb` to the test suite, 55 passing examples, 34 failed. It seems that to fix these failing specs `Opal.gvars` should be replaced to something more complex that just a plain JS object

**Comment by elia** [comment]
> It seems that to fix these failing specs Opal.gvars should be replaced to something more complex that just a plain JS object

Yes, an alternative could be to do it at compile-time, especially for those bound to a scope. Anyway those vars and their behavior is kinda obscure to most developers and I honestly wonder how many people know about them. I think once we support the most common ones we can safely postpone the others.

**Pull request merged**
