### PR TITLE
[WIP] [Experimental] Bridge Hash to Map

### PR DESCRIPTION
**Pull request by janbiedermann**
use Javascript Map class as Opal Hash

currently partially working

### CODE REVIEW

**Comment by janbiedermann** [comment]
Why use Map?
- keeps order of assignment like Hash
- can use any js type/object as key, like Hash
- is in some cases even faster than JS Objects
- for sure faster than maintaining 2 Objects and a Array, what Hash currently does internally
- saves some code, as all the code for maintaining 2 Objects and a Array can go

**Comment by hmdne** [comment]
I was working on a similar patchset. One thing to note is that...

Ruby hash has 2 modes:
- compare_by_identity - `#__id__` semantics (this I think may be close to what JS does)
- default - `#hash` and `#eql?` semantics for Hash (internally Ruby creates a number of buckets keyed by `#hash` and additionally checks `#eql?`)

This patchset would break both of those semantics. Question is if that's OK for us.

**Comment by janbiedermann** [comment]
And another problem is the "key by reference"-issue:
```
m.set([1], 2)
m.get([1]) => undefined

a = [1]
m.set(a, 2)
m.get(a) => [1]
```

still needs a workaround for that.

**Comment by janbiedermann** [comment]
So non literal Hash key access may be slow, as it walks through keys comparing them. That unfortunatley includes JS Symbol and others, so these may need conversion to a literal, as future optimization if JS Symbol is used as Ruby Symbol or something else.

**Comment by janbiedermann** [comment]
Ruy Hash specs test for certain implementation details, that, using Map as bridged Class, are not necessary to be implemented and executed. Implementing them would even hurt performance. Anyway, Hash < Map is possible, can be made to work, would probably work well enough, saves some code, but because of missing spec compliance i will pause this attempt and look for another way.

**Comment by janbiedermann** [comment]
Closing in favour of #2563

**Pull request closed without merging**
