### PR TITLE
add Numbers into Unsupported Features

### PR DESCRIPTION
**Pull request by takahashim**
Related to https://github.com/opal/opal.github.io/issues/21 and https://github.com/opal/opal/issues/896

### CODE REVIEW

**Comment by meh** [comment]
That sounds a little misleading to me.

Opal does support numbers, it just doesn't support strongly typed numerics like Ruby does, there's a single class for `Float` and `Integer`, but there are classes for `Complex` and `Rational`.

**Comment by takahashim** [comment]
@meh thanks for your feedback!
Should I rename the title as `#### Integer and Float type system ####` instead of `#### Numbers ####`?

**Comment by elia** [comment]
@takahashim yes, maybe something like `Integer / Float difference`. 
Also can you please expand the explanation with what @meh added and remove the `method_added`/`method_removed` as they're now supported?

**Comment by takahashim** [comment]
@elia Thanks!  I fixed it.
And I'll send another PR to remove `method_added` and `method_removed` from the document.

**Comment by elia** [comment]
Thank you!

**Pull request merged**
