### PR TITLE
optimize Regexp#match and Regexp#match? when pos is undefined

### PR DESCRIPTION
**Pull request by mojavelinux**
- use original regexp when pos is not defined

### CODE REVIEW

**Comment by mojavelinux** [comment]
When pos is not defined, there's no reason to build the regexp again as we know we're looking for the first match from the start of the string.

**Comment by iliabylich** [comment]
Looks good! Could you add some tests for this functionality somewhere in `spec/opal/core/regexp/match_spec.rb`? From what I understand now `Regexp#match` calls `exec` only once when `pos` is not specified. Maybe the test could be something like:
``` ruby
describe 'Regexp#match' do
  describe 'when pos is not specified' do
    it 'calls .exec only once on the current object' do
      regexp = /test/
      count = 0
      `regexp.exec = function(s) { count++ }`
      regexp.match('test test')
      count.should == 1
    end
  end
end
```
And you can run it with `env PATTERN=spec/opal/core/regexp/match_spec.rb bundle exec rake mspec_opal_nodejs`

**Comment by mojavelinux** [comment]
Yep, I can add a test.

**Comment by mojavelinux** [comment]
Tests added. I think you'll like them.

While writing the tests, I realized that pos is not even supported by Opal's Regexp#match?. That will need to be a follow-up issue. There's a stub assertion in there once it is implemented.

**Comment by iliabylich** [comment]
Thank you for this high quality PR!

**Comment by mojavelinux** [comment]
Thank you for being welcoming and making it easy to contribute!

**Pull request merged**
