### PR TITLE
Use arity for block length if available

### PR DESCRIPTION
**Pull request by iamprich**
This pull request aims to solve issue #1907. By checking to see if `block.$$arity` is available, we ensure that any block parameters containing a splat operator will have the correct length. JavaScript functions will continue to use `block.length`.

### CODE REVIEW

**Comment by iamprich** [comment]
I'm not completely understanding the failure and can't find it in the files. I manually patched and tested this pull request in try opal as well as a production rails app and everything seemed to work fine.

**Comment by elia** [comment]
> I'm not completely understanding the failure and can't find it in the files. I manually patched and tested this pull request in try opal as well as a production rails app and everything seemed to work fine.

That's fine, this is one of the trickiest part of Ruby, and the Ruby Spec catches a number of corner cases that are very unlikely in most codebases. I'll look into that and see if I can give you any hint on how to fix that test, but maybe you'll get there first 🙂. 

Meanwhile, thanks for your contribution! Feel free to ask if you bump into anything that's too obscure or for any guidance 👍

**Comment by iamprich** [comment]
I managed to find the cause of the failure, which is related to how `arity` deals with optional arguments (splat or keyword).

A solution would be to remove `Math.abs` and instead deconstruct if `block_length` has a value of `< 0` or `> 1`

So a (not super pretty) fix would look like
```
var block_length = (block.$$arity ? block.$$arity : block.length)

...

if (((block_length > 1 || block_length < 0) || (has_trailing_comma && block_length === 1)) && arg.$$is_array) {
      return block.apply(null, arg);
    }
}
```
When reproducing the failing test in try opal, this solution returned the expected value and passed my production rails app test. I'm attempting to refactor the code to read a little better before pushing my changes.

Thanks for making yourself available for any questions! I'm sure I'll come up with a few.

**Comment by iamprich** [comment]
Well, the one failing test is now passing.... but I seemed to have spawned 18 new failing test :disappointed_relieved:

I just set up the test environment locally, which I should have done in the first place. Sorry about that. 

Hopefully I can get this all green!

**Comment by hmdne** [comment]
I rebased this to the current master with a new PR #2250. I would rather force push it... but the repo vanished.

**Pull request closed without merging**
