### PR TITLE
Number#=== is called instead of Kernel#=== on switch/case with Numeric

### LINKED ISSUE #1639: Kernel#=== is called on Numeric comparison (switch/case)
Follow-up: https://github.com/opal/opal/pull/1628

#### How to reproduce

.numeric-switch.rb
```ruby
value = 12

case value 
when 80 then
  p 'Hello!'
else
  p 'Bonjour!'
end
```

Edit `opal/corelib/kernel.rb`

```diff
   def ===(other)
+    p 'Kernel#=== is called'
     self.object_id == other.object_id || self == other
   end
```

Run!

```
bundle exec opal -- numeric-switch.rb 
```
```
"Kernel#=== is called"
"Bonjour!"
```

### PR DESCRIPTION
**Pull request by Mogztter**
Resolves #1639

### CODE REVIEW

**Comment by meh** [comment]
Guess I was too eager to merging because I was going to do a couple changes to `Numeric` 🐼 

Apparently everything breaks with this.

**Comment by Mogztter** [comment]
Yes I'm looking at Travis right now, sorry about that 😕

**Comment by Mogztter** [comment]
I think it's better to revert my changes

**Comment by meh** [comment]
Yeah, reverted, my bad for being so eager 🐼 

The change just looked so innocent, I think it even brought the specs into an infinite loop or something.

**Pull request merged**
