### PR TITLE
Add a continue to break the current iteration when using redo

### LINKED ISSUE #1816: redo in "unterminated" while is not working
## Reproduction case with "unterminated" while

Let's consider the following code:

**redo.rb**
```rb
count = 0
while true
  p 'a'
  count += 1
  if count == 1
    redo
  end
  p 'b'
  break;
end
```

**MRI (Ruby 2.4.1)**

```
ruby redo.rb 
"a"
"a"
"b"
````

**Opal master**

```
bundle exec opal redo.rb
"a"
"b"
````

As you can see `redo` was "ignored" and the second "a" letter is missing.
The generated code is:

```js
count = 0;
$a = false; while ($a || $truthy(true)) {$a = false;
    
  self.$p("a");
  count = $rb_plus(count, 1);
  if (count['$=='](1)) {
    $a = true};
  self.$p("b");
  break;;
};
```

Instead of calling the loop again, the code is changing the value of `$a` to `true`.

## Working example with for loop

Please note that if we replace the "unterminated" while loop by a for loop then it's working:

**redo-loop.rb**
```rb
count = 0
(0..5).each do |i|
  p 'a'
  count += 1
  if count == 1
    redo
  end
  p 'b'
  break;
end
```
```
bundle exec opal redo-loop.rb             
"a"
"a"
"b"
```

In this case the generated code looks fine (with a `TMP_1` function called on `redo`). Here's a simplified version of the generated code:

```js
$send($range(0, 5, false), 'each', [], (TMP_1 = function (i) {
  this.$p("a");
  count = $rb_plus(count, 1);
  if (count['$=='](1)) {
    return TMP_1.apply(null, $slice.call(arguments))
  }
  this.$p("b");
  Opal.brk(nil, Opal.new_brk());
}));
```

### PR DESCRIPTION
**Pull request by Mogztter**
Resolves #1816

### CODE REVIEW

**Comment by Mogztter** [comment]
The failure on Appveyor is: 
```
TestBenchmark#test_realtime_output [Assertion: Expected 1 to be < 0.9990899999999998.]:
Expected 1 to be < 0.9990899999999998
```

What? :confused:

**Comment by Mogztter** [comment]
No worries, with your explanations it was an easy fix :+1: 
Do you know what's up with `TestBenchmark#test_realtime_output` on AppVeyor ?

**Comment by iliabylich** [comment]
> Do you know what's up with TestBenchmark#test_realtime_output on AppVeyor ? I can't restart the build on AppVeyor (maybe it's "just" an intermittent failure ?)

1. It fails only on windows
2. the previous bulid (https://ci.appveyor.com/project/elia/opal/build/808) was green, and is was built 1 few minutes ago.

Looks like your code has some conflicts with the windows-specific part of the test suite.

**Comment by Mogztter** [comment]
Ok investigating :nerd_face:

**Comment by iliabylich** [comment]
> I can't reproduce this issue on AppVeyor using my branch

Good to know. If it's related to some specific order of running specs I believe we can merge this PR and create a separate issue for investigating. Hope it can be reproduced on linux/mac 😄 

Also I'm not sure that MRI suite is randomized. If it is that we are good to go. Otherwise setting a `RANDOM_SEED` variable has no effect.

**Comment by iliabylich** [comment]
Yes, `RANDOM_SEED` doesn't work for minitest suite:
```
$ env bundle exec rake minitest_nodejs
Waiting for server…
Connecting to localhost:4567...
Connecting to localhost:4567...
Connecting to localhost:4567...
Connecting to localhost:4567...
Connecting to localhost:4567...
== Sinatra (v2.0.1) has taken the stage on 4567 for development with backup from Puma
Puma starting in single mode...
* Version 3.11.3 (ruby 2.5.1-p57), codename: Love Song
* Min threads: 0, max threads: 16
* Environment: development
* Listening on tcp://localhost:4567
Use Ctrl-C to stop
Connecting to localhost:4567...
Server ready.
export RANDOM_SEED=20872 # to re-use the same randomization
ruby -rbundler/setup exe/opal -ghike -Itest -Ilib -Ivendored-minitest -Itest/cruby/test -soptparse -sio/console -stimeout -smutex_m -srubygems -stempfile -smonitor -Rnodejs -Dwarning -A --enable-source-location tmp/minitest_cruby_nodejs.rb
Object freezing is not supported by Opal
Run options: --seed 28908
```

**Comment by iliabylich** [comment]
@Mogztter Could you include this patch into PR please?
```
--- a/vendored-minitest/minitest.rb
+++ b/vendored-minitest/minitest.rb
@@ -204,7 +204,7 @@ module Minitest

     unless options[:seed] then
       srand
-      options[:seed] = (ENV["SEED"] || srand).to_i % 0xFFFF
+      options[:seed] = (ENV["RANDOM_SEED"] || srand).to_i % 0xFFFF
       orig_args << "--seed" << options[:seed].to_s
     end
```

It allows running:
```
$ RANDOM_SEED=1 env bundle exec rake minitest_nodejs
Waiting for server…
Connecting to localhost:4567...
Connecting to localhost:4567...
Connecting to localhost:4567...
Connecting to localhost:4567...
Connecting to localhost:4567...
== Sinatra (v2.0.1) has taken the stage on 4567 for development with backup from Puma
Puma starting in single mode...
* Version 3.11.3 (ruby 2.5.1-p57), codename: Love Song
* Min threads: 0, max threads: 16
* Environment: development
* Listening on tcp://localhost:4567
Use Ctrl-C to stop
Connecting to localhost:4567...
Server ready.
export RANDOM_SEED=1 # to re-use the same randomization
ruby -rbundler/setup exe/opal -ghike -Itest -Ilib -Ivendored-minitest -Itest/cruby/test -soptparse -sio/console -stimeout -smutex_m -srubygems -stempfile -smonitor -Rnodejs -Dwarning -A --enable-source-location tmp/minitest_cruby_nodejs.rb
Object freezing is not supported by Opal
Run options: --seed 1
```

And by the way I can't reproduce the failure on your branch with `RANDOM_SEED=50854`. Let's see how it work on CI

**Comment by Mogztter** [comment]
@iliabylich I added your patch and cleaned up my commits

**Comment by iliabylich** [comment]
Now it's green. Weird, looks like we have conflicting specs.

**Comment by iliabylich** [comment]
Thanks!

**Pull request merged**
