### PR TITLE
String#rindex fully compliant with rubyspec

### PR DESCRIPTION
**Pull request by vais**

### CODE REVIEW

**Comment by elia** [comment]
@vais any reason you're picking one letter var names? `var i, m, r, _m;`

**Comment by vais** [comment]
Because [naming things is hard](http://martinfowler.com/bliki/TwoHardThings.html) :) I'll try to do a better job of it in the future - my names tend to be either way too long or way too short.

**Comment by elia** [comment]
Of course the truth is there are 10 hard things is CS…

IMO you can safely go with "too long", itt easier to discard information than it is to create it afterwards

**Comment by ylluminate** [comment]
:+1: LOL

**Pull request merged**
