### PR TITLE
fixing source maps for 0.7

### PR DESCRIPTION
**Pull request by elia**

### CODE REVIEW

**Comment by elia** [comment]
no more WIP, @adambeynon @meh wanna do a quick review?

cc @ryanstout @catmando @vais

**Comment by ryanstout** [comment]
@elia this looks great.  I really want to check it out, but I probably won't get to it until next week.

**Comment by jaredcwhite** [comment]
@elia I tried this out on a new branch of a major production site I've been working on, and I'm not getting any errors or anything, but it's not actually doing anything. It's as if source_map_enabled is false, even though I'm not setting it to false and it's even set to true in application.rb just to test.

Looking at the JS files being generated, I don't think they have the source map data at the bottom for the browser to parse. Know of any reason why it wouldn't be adding the source map data?

BTW, I'm on Rails 4.1.9 at present, Sprockets 2.11.0, and Sprockets-Rails 2.2.4

**Comment by elia** [comment]
I still have to finish up the matching opal-rails branch, stay tuned 🎯

**Comment by elia** [comment]
@jaredcwhite give a  try again to opal/opal-rails#40 ;)

**Comment by jaredcwhite** [comment]
@elia NICE!!! This is the happiest thing for me all day, besides a beer. :) :beer:

**Comment by elia** [comment]
Let me know how it goes (with the code, not the beer)

**Comment by elia** [comment]
Merged as part of #773

**Pull request merged**
