### PR TITLE
Make REPL actually very useful

### PR DESCRIPTION
**Pull request by hmdne**
Just having some fun with REPL:

```ruby
[user@localhost opal]# bin/opal-repl
>> error
<anonymous>:1434:35:in `constructor.method_missing_stub': undefined method `error' for main (NoMethodError)
	from <anonymous>:9:53:in `undefined'
	from <anonymous>:10:3:in `undefined'
	from <anonymous>:41:11:in `undefined'
>> syntax^^^error
(irb):1:8: error: unexpected token tCARET
(irb):1: syntax^^^error
(irb):1:        ^      
>> if true
..   5
.. end
=> 5
>> `{}`
=> [object Object] => {}
>> ls 123
Comparable#methods: between?  clamp
Numeric#methods: __coerced__  clone  conj  conjugate  div  dup  i  imag  imaginary  polar  pretty_print  pretty_print_cycle  real  real?  rect  rectangular  step  to_c
Number#methods: %  &  *  **  +  +@  -  -@  /  <  <<  <=  <=>  ==  ===  >  >=  >>  []  ^  __id__  abs  abs2  allbits?  angle  anybits?  arg  bit_length  ceil  chr  coerce  denominator  digits  divmod  downto  eql?  equal?  even?  fdiv  finite?  floor  gcd  gcdlcm  infinite?  inspect  instance_of?  integer?  is_a?  kind_of?  lcm  magnitude  modulo  nan?  negative?  next  nobits?  nonzero?  numerator  object_id  odd?  ord  phase  positive?  pow  pred  quo  rationalize  remainder  round  size  succ  times  to_f  to_i  to_int  to_r  to_s  truncate  upto  zero?  |  ~
>> 
```

### CODE REVIEW

**Comment by hmdne** [comment]
image
It's colorful now!

**Comment by zw963** [comment]
It works, thank you.

```
>> require 'hello'
/home/zw963/.rvm/gems/ruby-3.0.2@marketbet_crawler/bundler/gems/opal-e14a932ffe0d/lib/opal/builder.rb:186:in `read': A file required by "(irb)" wasn't found. (Opal::Builder::MissingRequire)
can't find file: "hello" in:
- /home/zw963/.rvm/gems/ruby-3.0.2@marketbet_crawler/bundler/gems/opal-e14a932ffe0d/opal
- /home/zw963/.rvm/gems/ruby-3.0.2@marketbet_crawler/bundler/gems/opal-e14a932ffe0d/stdlib
- /home/zw963/.rvm/gems/ruby-3.0.2@marketbet_crawler/bundler/gems/opal-e14a932ffe0d/lib
- /home/zw963/.rvm/gems/ruby-3.0.2@marketbet_crawler/gems/ast-2.4.2/lib
- /home/zw963/.rvm/gems/ruby-3.0.2@marketbet_crawler/gems/ast-2.4.2/lib
- /home/zw963/.rvm/gems/ruby-3.0.2@marketbet_crawler/gems/parser-3.0.2.0/lib

With the following extensions:
- .js
- .js.js
- .rb
- .js.rb
- .opal
- .js.opal
- .opalerb
- .js.opalerb
- .erb
- .js.erb

And the following processors:
- Opal::BuilderProcessors::JsProcessor
- Opal::BuilderProcessors::RubyProcessor
- Opal::BuilderProcessors::OpalERBProcessor
- Opal::BuilderProcessors::ERBProcessor
        from /home/zw963/.rvm/gems/ruby-3.0.2@marketbet_crawler/bundler/gems/opal-e14a932ffe0d/lib/opal/builder.rb:200:in `process_require'
        from /home/zw963/.rvm/gems/ruby-3.0.2@marketbet_crawler/bundler/gems/opal-e14a932ffe0d/lib/opal/builder.rb:98:in `block in build_str'
        from /home/zw963/.rvm/gems/ruby-3.0.2@marketbet_crawler/bundler/gems/opal-e14a932ffe0d/lib/opal/builder.rb:98:in `map'
        from /home/zw963/.rvm/gems/ruby-3.0.2@marketbet_crawler/bundler/gems/opal-e14a932ffe0d/lib/opal/builder.rb:98:in `build_str'
        from /home/zw963/.rvm/gems/ruby-3.0.2@marketbet_crawler/bundler/gems/opal-e14a932ffe0d/lib/opal/repl.rb:126:in `block in eval_ruby'
        from /home/zw963/.rvm/gems/ruby-3.0.2@marketbet_crawler/bundler/gems/opal-e14a932ffe0d/lib/opal/repl.rb:95:in `silence'
        from /home/zw963/.rvm/gems/ruby-3.0.2@marketbet_crawler/bundler/gems/opal-e14a932ffe0d/lib/opal/repl.rb:125:in `eval_ruby'
        from /home/zw963/.rvm/gems/ruby-3.0.2@marketbet_crawler/bundler/gems/opal-e14a932ffe0d/lib/opal/repl.rb:64:in `run_line'
        from /home/zw963/.rvm/gems/ruby-3.0.2@marketbet_crawler/bundler/gems/opal-e14a932ffe0d/lib/opal/repl.rb:73:in `run_input_loop'
        from /home/zw963/.rvm/gems/ruby-3.0.2@marketbet_crawler/bundler/gems/opal-e14a932ffe0d/lib/opal/repl.rb:39:in `run'
        from /home/zw963/.rvm/gems/ruby-3.0.2@marketbet_crawler/bundler/gems/opal-e14a932ffe0d/exe/opal-repl:5:in `<top (required)>'
        from /home/zw963/.rvm/gems/ruby-3.0.2@marketbet_crawler/bin/opal-repl:23:in `load'
        from /home/zw963/.rvm/gems/ruby-3.0.2@marketbet_crawler/bin/opal-repl:23:in `<main>'
        from /home/zw963/.rvm/rubies/ruby-3.0.2/bin/ruby_executable_hooks:22:in `eval'
        from /home/zw963/.rvm/rubies/ruby-3.0.2/bin/ruby_executable_hooks:22:in `<main>'
/home/zw963/.rvm/gems/ruby-3.0.2@marketbet_crawler/bundler/gems/opal-e14a932ffe0d/lib/opal/builder.rb:186:in `read': can't find file: "hello" in: (Opal::Builder::MissingRequire)
- /home/zw963/.rvm/gems/ruby-3.0.2@marketbet_crawler/bundler/gems/opal-e14a932ffe0d/opal
- /home/zw963/.rvm/gems/ruby-3.0.2@marketbet_crawler/bundler/gems/opal-e14a932ffe0d/stdlib
- /home/zw963/.rvm/gems/ruby-3.0.2@marketbet_crawler/bundler/gems/opal-e14a932ffe0d/lib
- /home/zw963/.rvm/gems/ruby-3.0.2@marketbet_crawler/gems/ast-2.4.2/lib
- /home/zw963/.rvm/gems/ruby-3.0.2@marketbet_crawler/gems/ast-2.4.2/lib
- /home/zw963/.rvm/gems/ruby-3.0.2@marketbet_crawler/gems/parser-3.0.2.0/lib

With the following extensions:
- .js
- .js.js
- .rb
- .js.rb
- .opal
- .js.opal
- .opalerb
- .js.opalerb
- .erb
- .js.erb

And the following processors:
- Opal::BuilderProcessors::JsProcessor
- Opal::BuilderProcessors::RubyProcessor
- Opal::BuilderProcessors::OpalERBProcessor
- Opal::BuilderProcessors::ERBProcessor
        from /home/zw963/.rvm/gems/ruby-3.0.2@marketbet_crawler/bundler/gems/opal-e14a932ffe0d/lib/opal/builder.rb:200:in `process_require'
        from /home/zw963/.rvm/gems/ruby-3.0.2@marketbet_crawler/bundler/gems/opal-e14a932ffe0d/lib/opal/builder.rb:98:in `block in build_str'
        from /home/zw963/.rvm/gems/ruby-3.0.2@marketbet_crawler/bundler/gems/opal-e14a932ffe0d/lib/opal/builder.rb:98:in `map'
        from /home/zw963/.rvm/gems/ruby-3.0.2@marketbet_crawler/bundler/gems/opal-e14a932ffe0d/lib/opal/builder.rb:98:in `build_str'
        from /home/zw963/.rvm/gems/ruby-3.0.2@marketbet_crawler/bundler/gems/opal-e14a932ffe0d/lib/opal/repl.rb:126:in `block in eval_ruby'
        from /home/zw963/.rvm/gems/ruby-3.0.2@marketbet_crawler/bundler/gems/opal-e14a932ffe0d/lib/opal/repl.rb:95:in `silence'
        from /home/zw963/.rvm/gems/ruby-3.0.2@marketbet_crawler/bundler/gems/opal-e14a932ffe0d/lib/opal/repl.rb:125:in `eval_ruby'
        from /home/zw963/.rvm/gems/ruby-3.0.2@marketbet_crawler/bundler/gems/opal-e14a932ffe0d/lib/opal/repl.rb:64:in `run_line'
        from /home/zw963/.rvm/gems/ruby-3.0.2@marketbet_crawler/bundler/gems/opal-e14a932ffe0d/lib/opal/repl.rb:73:in `run_input_loop'
        from /home/zw963/.rvm/gems/ruby-3.0.2@marketbet_crawler/bundler/gems/opal-e14a932ffe0d/lib/opal/repl.rb:39:in `run'
        from /home/zw963/.rvm/gems/ruby-3.0.2@marketbet_crawler/bundler/gems/opal-e14a932ffe0d/exe/opal-repl:5:in `<top (required)>'
        from /home/zw963/.rvm/gems/ruby-3.0.2@marketbet_crawler/bin/opal-repl:23:in `load'
        from /home/zw963/.rvm/gems/ruby-3.0.2@marketbet_crawler/bin/opal-repl:23:in `<main>'
        from /home/zw963/.rvm/rubies/ruby-3.0.2/bin/ruby_executable_hooks:22:in `eval'
        from /home/zw963/.rvm/rubies/ruby-3.0.2/bin/ruby_executable_hooks:22:in `<main>'
>> 
```

though, the backtrace is a little longer,  is there a config like `RB.conf[:BACK_TRACE_LIMIT]` ?

**Comment by zw963** [comment]
And, just for curious, is it possible exists a `binding.irb` like command, which can break current app, and load Opal environment somewhere just like `opal-repl` does?

I know there is a gem named opal-irb, but, it not work anymore.

**Comment by hmdne** [comment]
@zw963 This would require the await patchset and would probably spell `binding.irb.await` to be feasible. It would be a good idea to implement this in some follow-up pull request.

**Pull request merged**
