### PR TITLE
Generated code optimization

### PR DESCRIPTION
**Pull request by hmdne**
This PR attempts to optimize the generated code. One may say, we have minifiers, but actually they don't do as good job as we may imagine. The benchmarks from the `performance` task will show that pretty clearly.

------

The first commit attempts to eliminate self definition (in def and iter) if it's not needed.

The rationale is that there are often functions that don't reference `self` and so possibly we can speed up performance a little.

### CODE REVIEW

**Comment by hmdne** [comment]
```
Comparison of the Asciidoctor (a real-life Opal application) compile and run:
                  Compile time: 6.239 -> 6.123 (change: -1.86%)
                      Run time: 0.285 -> 0.284 (change: -0.10%)
                   Bundle size: 5257437 -> 5236087 (change: -0.41%)
          Minified bundle size: 1264503 -> 1254455 (change: -0.79%)
```

Not much for speed improvement, but bundle size reduction is significant.

**Comment by hmdne** [comment]
I will repurpose this block for other compiler optimizations for now... will clean it up later.

**Comment by hmdne** [comment]
Source: `def a &block; end`

Before:

```
  return (Opal.def(self, '$a', $a$1 = function $$a() {
    var $iter = $a$1.$$p, block = $iter || nil, self = this;

    if ($iter) $a$1.$$p = null;
    
    
    if ($iter) $a$1.$$p = null;;
    return nil;
  }, $a$1.$$arity = 0), nil) && 'a'
```

After:

```
  return (Opal.def(self, '$a', $a$1 = function $$a() {
    var block = $a$1.$$p || nil;

    if (block) $a$1.$$p = null;
    
    ;
    return nil;
  }, $a$1.$$arity = 0), nil) && 'a'
```

Performance changes (master -> after those 2 commits):

```
Comparison of the Asciidoctor (a real-life Opal application) compile and run:
                  Compile time: 6.225 -> 6.074 (change: -2.43%)
                      Run time: 0.285 -> 0.283 (change: -0.68%)
                   Bundle size: 5257437 -> 5220199 (change: -0.71%)
          Minified bundle size: 1264503 -> 1244281 (change: -1.60%)
```

**Comment by hmdne** [comment]
Now, this is a real omission:

`}, $a$1.$$arity = 0), nil) && 'a'`

Why is nil there? If course, because of the earlier behavior of `def` returning nil.

**Comment by hmdne** [comment]
So, why we don't go even further? Let's helperize Opal.def and Opal.defs:

```
  var $a$1, self = Opal.top, $nesting = [], nil = Opal.nil, $$$ = Opal.$$$, $$ = Opal.$$, $def = Opal.def;

  return ($def(self, '$a', $a$1 = function $$a() {
    var block = $a$1.$$p || nil;

    if (block) $a$1.$$p = null;
    
    ;
    return nil;
  }, $a$1.$$arity = 0), 'a')
```


```
Comparison of the Asciidoctor (a real-life Opal application) compile and run:
                  Compile time: 6.232 -> 6.103 (change: -2.08%)
                      Run time: 0.283 -> 0.283 (change: -0.19%)
                   Bundle size: 5257437 -> 5214022 (change: -0.83%)
          Minified bundle size: 1264503 -> 1238407 (change: -2.06%)
```

That's quite a solid gain!

**Comment by hmdne** [comment]
Optimize slice & splice. This is pretty simple.

For a source like: `def a(*args); end` there was a call like this:

```
    $post_args = Opal.slice.call(arguments, 0, arguments.length);
```

Now it's just:

```
    $post_args = Opal.slice.call(arguments);
```

```
 Comparison of the Asciidoctor (a real-life Opal application) compile and run:
                  Compile time: 6.213 -> 6.107 (change: -1.71%)
                      Run time: 0.285 -> 0.282 (change: -0.81%)
                   Bundle size: 5257437 -> 5209571 (change: -0.91%)
          Minified bundle size: 1264503 -> 1234386 (change: -2.38%)
```

**Comment by janbiedermann** [comment]
Fantastic!

**Comment by hmdne** [comment]
What happened here? :O [work in progress]

```
Comparison of the Asciidoctor (a real-life Opal application) compile and run:
                  Compile time: 6.233 -> 6.083 (change: -2.40%)
                      Run time: 0.287 -> 0.280 (change: -2.36%)
                   Bundle size: 5257437 -> 5090149 (change: -3.18%)
          Minified bundle size: 1264503 -> 1109682 (change: -12.24%)
```

**Comment by hmdne** [comment]
Additional optimization, if we only want to set $$arity (which is - most of the time), then we don't pass an object, but integer.

```
Opal.queue(function(Opal) {/* Generated by Opal 1.3.1 */
  var self = Opal.top, $nesting = [], nil = Opal.nil, $$$ = Opal.$$$, $$ = Opal.$$, $def = Opal.def;

  return ($def(self, '$a', function $$a() {
    var block = $$a.$$p || nil;

    if (block) $$a.$$p = null;
    
    ;
    return nil;
  }, 0), 'a')
});
```

```
Comparison of the Asciidoctor (a real-life Opal application) compile and run:
                  Compile time: 6.249 -> 6.058 (change: -3.05%)
                      Run time: 0.286 -> 0.279 (change: -2.17%)
                   Bundle size: 5257437 -> 5036072 (change: -4.21%)
          Minified bundle size: 1264503 -> 1089609 (change: -13.83%)
```

**Comment by hmdne** [comment]
Use a delete statement instead of setting null to $$p. I'm not entirely sure it's more performant, especially that this may cause a change of a shape.

The same code now becomes:

```
Opal.queue(function(Opal) {/* Generated by Opal 1.3.1 */
  var self = Opal.top, $nesting = [], nil = Opal.nil, $$$ = Opal.$$$, $$ = Opal.$$, $def = Opal.def;

  return ($def(self, '$a', function $$a() {
    var block = $$a.$$p || nil;

    delete $$a.$$p;
    
    ;
    return nil;
  }, 0), 'a')
});
```

```
 Comparison of the Asciidoctor (a real-life Opal application) compile and run:
                  Compile time: 6.239 -> 6.057 (change: -2.92%)
                      Run time: 0.286 -> 0.280 (change: -2.03%)
                   Bundle size: 5257437 -> 5032881 (change: -4.27%)
          Minified bundle size: 1264503 -> 1087119 (change: -14.03%)
```

**Comment by hmdne** [comment]
Why can't `Opal.def` return a method name? Now it does:

```
Opal.queue(function(Opal) {/* Generated by Opal 1.3.1 */
  var self = Opal.top, $nesting = [], nil = Opal.nil, $$$ = Opal.$$$, $$ = Opal.$$, $def = Opal.def;

  return $def(self, '$a', function $$a() {
    var block = $$a.$$p || nil;

    delete $$a.$$p;
    
    ;
    return nil;
  }, 0)
});
```

Looks like we are a little down in performance. I'm not sure if this particular patch is the reason.

```
Comparison of the Asciidoctor (a real-life Opal application) compile and run:
                  Compile time: 6.253 -> 6.145 (change: -1.73%)
                      Run time: 0.285 -> 0.280 (change: -1.61%)
                   Bundle size: 5257437 -> 5028381 (change: -4.36%)
          Minified bundle size: 1264503 -> 1086206 (change: -14.10%)
```

**Comment by hmdne** [comment]
I will later check performance improvements more thoroughly. This is a small change, but in a trend of renaming often called core methods.

```
Comparison of the Asciidoctor (a real-life Opal application) compile and run:
                  Compile time: 6.225 -> 6.141 (change: -1.34%)
                      Run time: 0.284 -> 0.279 (change: -1.77%)
                   Bundle size: 5257437 -> 5026654 (change: -4.39%)
          Minified bundle size: 1264503 -> 1085436 (change: -14.16%)
```

**Comment by hmdne** [comment]
After pushing this approach near its limit, we have the following results:

```
Comparison of the Asciidoctor (a real-life Opal application) compile and run:
                  Compile time: 6.258 -> 6.068 (change: -3.04%)
                      Run time: 0.287 -> 0.280 (change: -2.47%)
                   Bundle size: 5257437 -> 5041275 (change: -4.11%)
          Minified bundle size: 1264503 -> 1083267 (change: -14.33%)
```

**Comment by hmdne** [comment]
Replaced the result of compiling ::String from `$$$("::", "String")` to simply `$$$("String")`. A shortpath has been added.

```
Comparison of the Asciidoctor (a real-life Opal application) compile and run:
                  Compile time: 6.192 -> 6.044 (change: -2.39%)
                      Run time: 0.285 -> 0.278 (change: -2.24%)
                   Bundle size: 5257437 -> 5021284 (change: -4.49%)
          Minified bundle size: 1264503 -> 1078370 (change: -14.72%)
```

**Comment by hmdne** [comment]
We have attained 15%! Can we go even further though?

```

Comparison of the Asciidoctor (a real-life Opal application) compile and run:
                  Compile time: 6.224 -> 6.048 (change: -2.82%)
                      Run time: 0.285 -> 0.277 (change: -2.58%)
                   Bundle size: 5257437 -> 5012188 (change: -4.66%)
          Minified bundle size: 1264503 -> 1072799 (change: -15.16%)
```

Let's take a look at this sample code from our corelib:

```ruby
class StandardError     < ::Exception; end
class EncodingError       < ::StandardError; end
class ZeroDivisionError   < ::StandardError; end
class NameError           < ::StandardError; end
class NoMethodError         < ::NameError; end
class RuntimeError        < ::StandardError; end
class FrozenError           < ::RuntimeError; end
class LocalJumpError      < ::StandardError; end
class TypeError           < ::StandardError; end
class ArgumentError       < ::StandardError; end
class UncaughtThrowError    < ::ArgumentError; end
class IndexError          < ::StandardError; end
```

Used to compile to this:

```javascript
Opal.queue(function(Opal) {/* Generated by Opal 1.3.1 */
  var self = Opal.top, $nesting = [], nil = Opal.nil, $$$ = Opal.$$$, $$ = Opal.$$, $klass = Opal.klass;

  
  (function($base, $super, $parent_nesting) {
    var self = $klass($base, $super, 'StandardError');

    var $nesting = [self].concat($parent_nesting);

    return nil
  })($nesting[0], $$$('::', 'Exception'), $nesting);
  (function($base, $super, $parent_nesting) {
    var self = $klass($base, $super, 'EncodingError');

    var $nesting = [self].concat($parent_nesting);

    return nil
  })($nesting[0], $$$('::', 'StandardError'), $nesting);
  (function($base, $super, $parent_nesting) {
    var self = $klass($base, $super, 'ZeroDivisionError');

    var $nesting = [self].concat($parent_nesting);

    return nil
  })($nesting[0], $$$('::', 'StandardError'), $nesting);
(...)
```

And now it compiles to this:

```javascript
Opal.queue(function(Opal) {/* Generated by Opal 1.3.1 */
  var self = Opal.top, $nesting = [], nil = Opal.nil, $$$ = Opal.$$$, $$ = Opal.$$, $klass = Opal.klass;

  
  ($klass($nesting[0], $$$('Exception'), 'StandardError'), nil);
  ($klass($nesting[0], $$$('StandardError'), 'EncodingError'), nil);
  ($klass($nesting[0], $$$('StandardError'), 'ZeroDivisionError'), nil);
  ($klass($nesting[0], $$$('StandardError'), 'NameError'), nil);
  ($klass($nesting[0], $$$('NameError'), 'NoMethodError'), nil);
  ($klass($nesting[0], $$$('StandardError'), 'RuntimeError'), nil);
  ($klass($nesting[0], $$$('RuntimeError'), 'FrozenError'), nil);
  ($klass($nesting[0], $$$('StandardError'), 'LocalJumpError'), nil);
  ($klass($nesting[0], $$$('StandardError'), 'TypeError'), nil);
  ($klass($nesting[0], $$$('StandardError'), 'ArgumentError'), nil);
  ($klass($nesting[0], $$$('ArgumentError'), 'UncaughtThrowError'), nil);
  return ($klass($nesting[0], $$$('StandardError'), 'IndexError'), nil);
});
```

It's much cleaner now, isn't it?

**Comment by hmdne** [comment]
```true unless false```

Was:

```
  if ($truthy(false)) {
  } else {
    true
  };
```

Is:

```
  if (!$truthy(false)) {
    true
  };
```

```
Comparison of the Asciidoctor (a real-life Opal application) compile and run:
                  Compile time: 6.164 -> 6.048 (change: -1.87%)
                      Run time: 0.284 -> 0.277 (change: -2.62%)
                   Bundle size: 5257437 -> 4994938 (change: -4.99%)
          Minified bundle size: 1264503 -> 1072746 (change: -15.16%)
```

**Comment by hmdne** [comment]
`a || b || c || d || e`

Was:
```
  if ($truthy(($ret_or_1 = (function() {if ($truthy(($ret_or_2 = (function() {if ($truthy(($ret_or_3 = (function() {if ($truthy(($ret_or_4 = self.$a()))) {
    return $ret_or_4
  } else {
    return self.$b()
  }; return nil; })()))) {
    return $ret_or_3
  } else {
    return self.$c()
  }; return nil; })()))) {
    return $ret_or_2
  } else {
    return self.$d()
  }; return nil; })()))) {
    return $ret_or_1
  } else {
    return self.$e()
  }
```

Is:

```
  if ($truthy(($ret_or_1 = ($truthy(($ret_or_2 = ($truthy(($ret_or_3 = ($truthy(($ret_or_4 = self.$a())) ? ($ret_or_4) : (self.$b())))) ? ($ret_or_3) : (self.$c())))) ? ($ret_or_2) : (self.$d()))))) {
    return $ret_or_1
  } else {
    return self.$e()
  }
```

Possibly the biggest runtime improvement, costing us a little bit of compile time though:

```
Comparison of the Asciidoctor (a real-life Opal application) compile and run:
                  Compile time: 6.269 -> 6.198 (change: -1.13%)
                      Run time: 0.286 -> 0.273 (change: -4.44%)
                   Bundle size: 5257437 -> 4868356 (change: -7.40%)
          Minified bundle size: 1264503 -> 1069576 (change: -15.42%)
```

**Comment by hmdne** [comment]
This commit simply compresses the unsupported.rb String part to a loop of define_methods. This causes Array#each and define_method to become compiled.

Comparison of the Asciidoctor (a real-life Opal application) compile and run:
                  Compile time: 6.090 -> 6.024 (change: -1.09%)
                      Run time: 0.285 -> 0.271 (change: -5.04%)
                   Bundle size: 5259054 -> 4857096 (change: -7.64%)
          Minified bundle size: 1264953 -> 1067375 (change: -15.62%)

**Comment by hmdne** [comment]
Empty top compilation, not much of a change though:

```
Comparison of the Asciidoctor (a real-life Opal application) compile and run:
                  Compile time: 6.109 -> 6.018 (change: -1.50%)
                      Run time: 0.285 -> 0.271 (change: -5.06%)
                   Bundle size: 5259054 -> 4856906 (change: -7.65%)
          Minified bundle size: 1264953 -> 1067299 (change: -15.63%)

**Comment by hmdne** [comment]
No tangible change this time, but at least we got rid of `eval` which should help the JS engines and minifiers a little bit. Related to #1939, but it touches a different area.

```
Comparison of the Asciidoctor (a real-life Opal application) compile and run:
                  Compile time: 6.071 -> 5.965 (change: -1.76%)
                      Run time: 0.285 -> 0.271 (change: -4.75%)
                   Bundle size: 5259054 -> 4856724 (change: -7.65%)
          Minified bundle size: 1264953 -> 1067161 (change: -15.64%)
```

**Comment by hmdne** [comment]
I noticed that certain parts or parser use expressions like `a || b || c` a lot. This caused a ton of $ret_or_x variable allocations. Now we clean them up giving us a nice headroom on the minified bundle size.

```
Comparison of the Asciidoctor (a real-life Opal application) compile and run:
                  Compile time: 6.110 -> 5.972 (change: -2.25%)
                      Run time: 0.286 -> 0.271 (change: -5.20%)
                   Bundle size: 5259054 -> 4826837 (change: -8.22%)
          Minified bundle size: 1264953 -> 1058462 (change: -16.32%)
```

**Comment by hmdne** [comment]
Aliasing things that happen multiple times help the JS minifiers - like Terser - because it can't rename eg. Opal.regexp, but absolutely it can rename $regexp.

```
Comparison of the Asciidoctor (a real-life Opal application) compile and run:
                  Compile time: 6.089 -> 6.006 (change: -1.36%)
                      Run time: 0.285 -> 0.269 (change: -5.39%)
                   Bundle size: 5259054 -> 4824589 (change: -8.26%)
          Minified bundle size: 1264953 -> 1054974 (change: -16.60%)

**Comment by hmdne** [comment]
If -m is passed to terser, the results of this patchset are a little less pronounced:

```
Comparison of the Asciidoctor (a real-life Opal application) compile and run:
                  Compile time: 6.081 -> 6.019 (change: -1.03%)
                      Run time: 0.284 -> 0.270 (change: -5.23%)
                   Bundle size: 5259054 -> 4824589 (change: -8.26%)
          Minified bundle size: 1264953 -> 1054974 (change: -16.60%)
            Mangled & minified: 812275 -> 732066 (change: -9.87%)

**Comment by hmdne** [comment]
Opal automatically sets the instance variables on a prototype. This is fine, but let's reduce the accesses to Opal.$$prototype by creating a helper variable $proto.

```
Comparison of the Asciidoctor (a real-life Opal application) compile and run:
                  Compile time: 6.086 -> 6.014 (change: -1.19%)
                      Run time: 0.284 -> 0.269 (change: -5.28%)
                   Bundle size: 5259054 -> 4823880 (change: -8.27%)
          Minified bundle size: 1264953 -> 1053776 (change: -16.69%)
            Mangled & minified: 812275 -> 730112 (change: -10.12%)

**Comment by hmdne** [comment]
It is much performant to split a string than to push large arrays with strings. This is what Closure Compiler does. Let's help a little our Terser users.

```
 Comparison of the Asciidoctor (a real-life Opal application) compile and run:
                  Compile time: 6.088 -> 6.008 (change: -1.30%)
                      Run time: 0.285 -> 0.271 (change: -5.08%)
                   Bundle size: 5259054 -> 4812284 (change: -8.50%)
          Minified bundle size: 1264953 -> 1044964 (change: -17.39%)
            Mangled & minified: 812275 -> 721296 (change: -11.20%)

**Comment by hmdne** [comment]
After this round of ::ization and possibly hiding $$ and $$$ just as we hide self...

```
Comparison of the Asciidoctor (a real-life Opal application) compile and run:
                  Compile time: 6.082 -> 5.964 (change: -1.94%)
                      Run time: 0.284 -> 0.270 (change: -4.92%)
                   Bundle size: 5259054 -> 4811653 (change: -8.51%)
          Minified bundle size: 1264953 -> 1041721 (change: -17.65%)
            Mangled & minified: 812275 -> 720161 (change: -11.34%)

**Comment by hmdne** [comment]
Let's not define $nesting if it's not needed...

```
Comparison of the Asciidoctor (a real-life Opal application) compile and run:
                  Compile time: 6.090 -> 5.952 (change: -2.27%)
                      Run time: 0.284 -> 0.269 (change: -5.26%)
                   Bundle size: 5259054 -> 4806185 (change: -8.61%)
          Minified bundle size: 1264953 -> 1036887 (change: -18.03%)
            Mangled & minified: 812275 -> 717787 (change: -11.63%)

**Comment by hmdne** [comment]
Let's create replace calls like $$($nesting, 'Something') with $r('Something') -- $r is a curried $$.

```
 Comparison of the Asciidoctor (a real-life Opal application) compile and run:
                  Compile time: 6.097 -> 5.976 (change: -1.99%)
                      Run time: 0.285 -> 0.270 (change: -5.41%)
                   Bundle size: 5259054 -> 4795627 (change: -8.81%)
          Minified bundle size: 1264953 -> 1027837 (change: -18.75%)
            Mangled & minified: 812275 -> 716231 (change: -11.82%)

**Comment by hmdne** [comment]
`"aaaa#{true}"`

Was:

`"" + "aaaa" + (true)`

Is:

`"aaaa" + (true)`

This changed nothing for Terser though.

```
 Comparison of the Asciidoctor (a real-life Opal application) compile and run:
                  Compile time: 6.087 -> 5.959 (change: -2.10%)
                      Run time: 0.284 -> 0.269 (change: -5.45%)
                   Bundle size: 5259054 -> 4783491 (change: -9.04%)
          Minified bundle size: 1264953 -> 1027837 (change: -18.75%)
            Mangled & minified: 812275 -> 716231 (change: -11.82%)

**Comment by hmdne** [comment]
After removing $parent_nesting if not needed:

```
Comparison of the Asciidoctor (a real-life Opal application) compile and run:
                  Compile time: 6.073 -> 5.956 (change: -1.92%)
                      Run time: 0.284 -> 0.269 (change: -5.46%)
                   Bundle size: 5259054 -> 4781496 (change: -9.08%)
          Minified bundle size: 1264953 -> 1026844 (change: -18.82%)
            Mangled & minified: 812275 -> 715972 (change: -11.86%)

**Review by elia — APPROVED** [review]
Needless to say this isi just awesome!

**Comment by hmdne** [comment]
Thanks! Merging this :D

**Pull request merged**
