### PR TITLE
Eliminate case node with a rewriter.

### PR DESCRIPTION
**Pull request by hmdne**
This needs to be made more readable, tests to be written... otherwise, it should fix a lot of issues like #2136, #1600

### CODE REVIEW

**Comment by elia** [comment]
This is great, the less nodes the better!

**Comment by hmdne** [comment]
In this PR I also took liberty to experiment a little bit :D

With that experiment I created a new "SimpleIf" node to return an expression not a statement if it's possible so that we could get rid of the closures where they aren't needed. A similar thing could be done to Begin statements. Thing is, this doesn't improve performance as I thought it would, it only cleans up the resulting code. Maybe a minifier like Terser or Google Closure Compiler could do a better job here.

Later I found out a way to implement FlipFlops, which aren't as used in Ruby as much, but as a continuation of the If node changes, I decided to implement them.

Actually, I think that rewriters aren't the best with regards to compiler performance. Since all of them run a DFS algorithm on the whole tree, maybe it could be beneficial to connect some (especially those simple ones) rewriters into a single rewriter (running all in parallel). Then I wouldn't have such concerns about performance. With a careful thought we may be able to achieve this without sacrificing the code quality.

**Comment by hmdne** [comment]
Right now I'm quite ambivalent about this. As in, reducing the number or Nodes is certainly with some benefits, but then, converting a when to a deeply nested if will cause an issue of a stack depth. Let's leave this patch for now, maybe revisit it in the future.

**Comment by hmdne** [comment]
What if: we didn't recurse?

**Comment by hmdne** [comment]
To note:
* Opal before allowed for about 5000 case branches for runtime on V8, virtually any number for compilation
* This branch reduces the number of case branches for compilation to 1700
* MRI breaks after 3000

Now I'm rebasing this atop of our compiler optimization branch; next I will do some optimizations for $truthy((x)['$==='](y))

**Comment by hmdne** [comment]
Has been merged in a better form.

**Pull request closed without merging**
