### PR TITLE
Regexp names

### PR DESCRIPTION
**Pull request by janbiedermann**

### CODE REVIEW

**Comment by iliabylich** [comment]
Could you check if there are any specs in the RubySpec suite that are green now? `env INVERT_RUNNING_MODE=true bundle exec rake mspec_ruby_nodejs` shows them, filters are in the `spec/filters/bugs/regexp.rb` directory.

**Comment by janbiedermann** [comment]
yes, named captures tests work, except one:
```
fails "Regexp#names returns each capture name only once" # Exception: Invalid regular expression: /n(?<cap>ee)d(?<cap>le)/: Duplicate capture group name
```
This exception comes from js. Not sure what to do? Catch in the initializer? But then the regexp is useless anyway within js.

**Comment by janbiedermann** [comment]
hit the wrong button

**Comment by hmdne** [comment]
Superseded by #2272

**Pull request closed without merging**
