### PR TITLE
TracePoint :class support.

### PR DESCRIPTION
**Pull request by janbiedermann**
TracePoint support for the :class event
https://ruby-doc.org/core-2.6/TracePoint.html

However, in ruby, when passing the class to the block, the method .self is available, but not in Opal:

Ruby:
https://github.com/fxn/zeitwerk/blob/ad26cb0521cfb88fd8fee687dca7eb10e4ccf1bc/lib/zeitwerk/explicit_namespace.rb#L62

Opal:
https://github.com/isomorfeus/opal-zeitwerk/blob/25d6dad02f9d4add101ca4e26220ca2a91bcea46/opal/zeitwerk/explicit_namespace.rb#L54

Otherwise usage is just as in ruby:
https://github.com/isomorfeus/opal-zeitwerk/blob/25d6dad02f9d4add101ca4e26220ca2a91bcea46/opal/zeitwerk/explicit_namespace.rb#L69

### CODE REVIEW

**Comment by janbiedermann** [comment]
I found the TracePoint  :class specs, only 2 of them, seems like i still need to adjust something ...

**Comment by janbiedermann** [comment]
Now correctly implemented with the one spec concerning the code running. `.self` properly working like in ruby. (I originally misunderstood what to pass to the event block.)
Not sure what to do about the one line to much on code climate.

**Comment by hmdne** [comment]
I rebased this to the latest master

**Comment by hmdne** [comment]
This is ready for a final review and hopefully a merge to kickstart the v1.3 development process :D

**Review by elia — APPROVED** [review]
This is amazing! 🤩 
(I'll cleanup/squash a couple of commits and then merge)

**Pull request merged**
