### PR TITLE
Optimize truthiness/falsiness checks

### PR DESCRIPTION
**Pull request by hmdne**
I noticed we were first comparing to nil, then !boolean || true. Unless
I'm missing something, all we need to do is make sure it's not false or
nil.

This is a rebase of #1097, I created a new PR because I can't force push to the old one.

### CODE REVIEW

**Comment by hmdne** [comment]
Booleans... how do they work

**Comment by hmdne** [comment]
This works now BUT: we can always get a boxed boolean via calls like Kernel#itself. And those booleans will be treated wrong. So I will try to continue this PR to ensure that boxing doesn't happen, for Booleans at least.

**Comment by hmdne** [comment]
In general - this patchset would make `new Boolean(false)` truthy. And we ensure Opal does not create such a monstrosity.

This also would fix false.itself/false.tap boxing the values, cc @catmando

**Comment by hmdne** [comment]
We are not getting this fully for v1.4. I will rework it slightly so we will at least get strict mode in a few modules to ensure we are not returning boxed values.

**Review by elia — APPROVED** [review]

**Pull request merged**
