### PR TITLE
Fix begin..else issue

### PR DESCRIPTION
**Pull request by wied03**
Update to latest ruby specs which test for this
Wasn't broken for blocks, only methods
Exclude new ruby specs that fail

https://github.com/opal/opal/issues/1518

### CODE REVIEW

**Comment by wied03** [comment]
@iliabylich - I looked and the old/pre-AST code didn't seem to check `stmt?` when it called `compiler.returns` for the rescue else code. Everything, including new specs, passed when I took it out. Do you see any reason why we can't remove it?

**Comment by iliabylich** [comment]
@wied03 The bug is in the `Compiler#returns`. For `:rescue` node it should wrap `else_sexp` with `returns()`. `begin; rescue; else` can be a statemnt, in this case we don't need to return `else`-value.

Try to compile the following code, looks like it doesn't work as expected with your patch:
``` ruby
begin
  1
rescue
  2
else
  3
end

:returning_value
```

Only `:expr` and `:recv` (i.e. not `:stmt`) begin-rescue-else nodes must return their `else`-values.

I guess the bug was introduced in #1465, AST was changed from `s(:rescue, s(:resbody, body_code))` to `s(:rescue, body_code)` and we missed it.

**Comment by wied03** [comment]
Perhaps, but how is the bug in compiler returns? The reason this didn't work in the first place is because compiler returns isn't called due to the guard condition. I don't know enough about the stmt piece here.

**Comment by wied03** [comment]
And if this PR leaves things in a broken state, we need more rubyspecs :)

**Comment by wied03** [comment]
But I do see that we're returning `3` with the PR instead of `returning_value`. I'll add some more rubyspecs and then can resume working on this.

**Comment by iliabylich** [comment]
@wied03 
``` ruby
obj.method(value)
```
`obj` here is a `:recv` (receiver)
`value` is an `:expr` (expression)
`object.value` is a `:stmt` (statement)

It could be possible to use only `:expr` and `:stmt`, but JS is JS.

There are only 3 places where Opal needs `:recv`:
+ numbers (to prevent generating a code like `1.toString()` - should be `(1).toString()`)
+ x-string (because it can contain absolutely everything)
+ dynamic string (same as x-string)

`:stmt` is the simplest level, this is the default level of compilation for each node. `:expr` and `:recv` are mostly used to wrap the code with parentheses and anonymous functions + JS returns.

In your case when `begin; rescue; else; end` is a statement there's no need to put `js_return` to the AST because nothing should be returned.
But when it's not a statement (i.e. receiver or expression) it must return rescue-value or else-value + sometimes it must be wrapped with anonymous function.

**Comment by wied03** [comment]
@iliabylich - In your last paragraph, are you disputing the bug that prompted this PR or just explaining?

**Comment by iliabylich** [comment]
Just saying what I accidentally did wrong in https://github.com/opal/opal/pull/1465 :smile:
``` ruby
# Compiler#returns
when :rescue
  body_sexp, *resbodies, else_sexp = sexp.children

  resbodies = resbodies.map do |resbody|
    returns(resbody)
  end

  sexp.updated(nil, [
    returns(body_sexp),
    *resbodies,
    returns(else_sexp)
  ])
```

**Comment by wied03** [comment]
The reason we have a bug though is this IS a statement AND it needs the return statement.

**Comment by wied03** [comment]
Since @iliabylich decided to fix this on their own, I'll close this.

**Pull request closed without merging**
