### PR TITLE
ensure 0.digits == [0]

### PR DESCRIPTION
**Pull request by janbiedermann**
taken from #2299

### CODE REVIEW

**Comment by hmdne** [comment]
There is problem with a === operator and self and I have a feeling it may cause a problem.

```js
> Object.prototype.itself = function() { return this; }
[Function (anonymous)]
> (5).itself()
[Number: 5]
> 5
5
> (5).itself() == 5
true
> (5).itself() === 5
false
> (5).itself() === (5).itself()
false
>

**Comment by hmdne** [comment]
It works though and I can't break it! Good!

**Comment by hmdne** [comment]
```js
Number.prototype.is_zero = function() {
  return this === 0;
}

Number.prototype.is_zero_strict = function() {
  "use strict";
  return this === 0;
}

console.log("is_zero: ", (0).is_zero())
console.log("is_zero_strict: ", (0).is_zero_strict())
```

Return:
```js
is_zero:  false
is_zero_strict:  true
```

**Comment by elia** [comment]
Thanks @janbiedermann, I added a couple fixes and merged!

**Pull request merged**
