### PR TITLE
runtime.js cleanup

### PR DESCRIPTION
**Pull request by elia**
Should improve naming for both sanity when developing and while looking at stack traces.
All constructor should now appear with an "_alloc" suffix in stack traces, although I'm not sure I covered all cases.

### CODE REVIEW

**Comment by iliabylich** [comment]
:+1: love this naming! stuff like `OpalClass`/`ClassClass` was unreadable :smile: . And also thanks for adding more `displayName` properties to anonymous functions.

Can we do something with [this](https://github.com/opal/opal/blob/elia/runtime-cleanup/opal/corelib/runtime.js#L605) place? When I was debugging an issue with modules/classes, I've found a sequence of `ctor` functions in the prototype chain of anonymous module, and of all them had a `ctor` display name, which makes debugging much more difficult.

**Comment by elia** [comment]
@iliabylich I happen to have another couple of commits locally that I didn't dare to push at ~3am :P

**Comment by elia** [comment]
@iliabylich pushed b733673, let me know if you catch any other improvements that can be made or pain points you experienced

> love this naming! stuff like OpalClass/ClassClass was unreadable  . And also thanks for adding more displayName properties to anonymous functions.

It's great to see I'm not alone wandering through the runtime :)

**Comment by iliabylich** [comment]
(Using your branch)

``` ruby
mod = Module.new
%x{
  while (mod.constructor !== Object) {
    console.log(mod);
    mod = mod.__proto__;
  }
}
```

The output is:
```
cli_runner.js:19023 SingletonClass_alloc {$$id: 256, $$proto: Object, $$is_module: true, $$class: singleton_class, $$super: singleton_class…}
cli_runner.js:19023 Superclass_alloc_proxy {}
cli_runner.js:19023 superclass_constructor {}
cli_runner.js:19023 superclass_constructor {}
cli_runner.js:19023 superclass_constructor {}
cli_runner.js:19023 alloc_proxy {$$class: singleton_class}
cli_runner.js:19023 alloc_proxy {$$class: singleton_class}
cli_runner.js:19023 alloc_proxy {$$class: singleton_class}
cli_runner.js:19023 BasicObject_alloc {$$class: singleton_class}
```

Is it possible to make it more readable? :smile: I mean, it's hard to track down the object structure, there are 4 proxy objects and 3 superclass constructors. Without putting 10 debuggers into `runtime.js` it's very hard to find out what's going on.

**Comment by iliabylich** [comment]
@elia These proxy objects are related to names classes:
+ the first one comes from the `Class` (which should be fixed after https://github.com/opal/opal/pull/1232)
+ the next comes from the `Module` class
+ the last one is related to the `BasicObject`

`displayName` doesn't work for objects, is there any way to change these `alloc_proxy` names to something readable? I know it can be done by assigning an object to a variable with eval-ed name :smile: 

And the last item in the prototype chain is full of method stubs, is it possible to mark it as a stub?

**Comment by iliabylich** [comment]
@elia Got the following structure for `Module.new` using `eval` :smile: :
```
cli_runner.js:19043 SingletonClass_alloc {$$id: 258, $$proto: Object, $$is_module: true, $$class: singleton_class, $$super: singleton_class…}
cli_runner.js:19043 Superclass_alloc_proxy {}
cli_runner.js:19043 superclass_constructor {}
cli_runner.js:19043 superclass_constructor {}
cli_runner.js:19043 superclass_constructor {}
cli_runner.js:19043 Module_alloc_proxy {$$class: singleton_class}
cli_runner.js:19043 Object_alloc_proxy {$$class: singleton_class}
cli_runner.js:19043 BasicObject_alloc_proxy {$$class: singleton_class}
cli_runner.js:19043 BasicObject_alloc {$$class: singleton_class}
```
But I can't find any solutions for changing JS object name on-the-fly without `eval`. Any ideas?

How about adding some field like `$$comesFrom` to these `alloc_proxy` objects? Like:
``` js
constructor.prototype = new alloc_proxy();
constructor.prototype.$$comesFrom = superklass;
```
That may give some information when inspecting an object

**Comment by elia** [comment]
The proto should point to the original superclass, anyway great feedback, can't wait to start implementing it tonight :full_moon_with_face: 

Please keep updating if you find other improvements that could be made! :)

**Comment by elia** [comment]
@iliabylich thanks again for the feedback, I decided to merge because I started a more deep refactor of the runtime that should make everything more straightforward and hopefully fix some bugs.

**Pull request merged**
