### PR TITLE
Fix method lookup on a Module when the same method was defined on a Class.

### LINKED ISSUE #1187: Class#method_name overrides Module#method_name
``` ruby
class Class
  def my_method
    puts "Called from Class"
  end
end

class Module
  def my_method
    puts "Called from Module"
  end
end

Module.new.my_method
Class.new.my_method
```
Prints
```
Called from Class
Called from Class
```

Tested on Opal master

### PR DESCRIPTION
**Pull request by iliabylich**
Closes #1187

### CODE REVIEW

**Comment by iliabylich** [comment]
I"m not sure, but it seems that `Module.new` was inherited from a `Class` (which is inherited from a `Module`). That's why it had both `Class`/`Module` methods. At least chrome inspector shows this prototype inheritance chain.

**Comment by elia** [comment]
Looks good, although I wonder if there's a way to test this without touching Module and Class directly. 

@meh any other comments?

**Comment by elia** [comment]
@iliabylich sorry, my last PR introduced some conflicts, can you rebase? I'll merge afterwards :)

**Comment by iliabylich** [comment]
@elia Done!

**Pull request merged**
