### PR TITLE
Bump version to 0.7.2 to correct RUBY_ENGINE_VERSION

### PR DESCRIPTION
**Pull request by supermario**
Refs opal/opal-cdn#6.

### CODE REVIEW

**Comment by supermario** [comment]
@elia wasn't sure if you wanted to adjust `CHANGELOG.md` to prevent confusion with present "edge (upcoming 0.7.2)" on master? Maybe a seperate PR...

**Comment by elia** [comment]
would be totally ok to keep the change in this PR

**Comment by elia** [comment]
@supermario just removed sprockets 3 support from 0.7 branch so you (or I) don't have to bother making it work :)

**Comment by elia** [comment]
@supermario can you please remove 4b9a2dd and add 8775c5213c (Specify node_modules path when running cruby tests)

**Comment by supermario** [comment]
@elia you've done all the work for me! I've just rebased off 0-7-stable.

Hope this is ok now.

Appreciate the help, sorry to have caused such a hassle over an integer!

**Comment by elia** [comment]
Happy to have fixed that, the more :eyes: on the project the better for everyone! :smile:

**Pull request merged**
