### PR TITLE
More informative error messages for unsupported mutable string methods

### PR DESCRIPTION
**Pull request by vais**

### CODE REVIEW

**Comment by adambeynon** [comment]
:+1: Much nicer.

**Comment by vais** [comment]
Thanks!

**Comment by Ajedi32** [comment]
Good to see some people are still getting work done, despite all the drama.

:+1: For clearer error messages.

**Comment by vais** [comment]
@Ajedi32 in the words of the immortal (and very much transgender if I recall correctly) Freddie Mercury, *the show must go on* :wink:

**Pull request merged**
