### PR TITLE
Fix Typo in `Running tests` Section of `README.md` File

### PR DESCRIPTION
**Pull request by og-mrk**
## Changes
* Removed the duplicated word `will` from the last sentence of `Running tests` section, which's inside `README.md` file.
   
   **Note:** The `README.md` noted above is the one inside Repo Root Folder, On the `master` Branch, which can be view by [clicking here](https://github.com/opal/opal/blob/master/README.md).

## Screenshot(s)
image
*Picture1: A screenshot to provide some context*

### CODE REVIEW

**Comment by og-mrk** [comment]
Also may I ask a question before reviewing and/or merging this PR
... Is this intended? or is it by accident?
image
Shouldn't these have the same Heading Levels, which looks like Level 3 (###) for every Sub-section of `Running tests`
Like `MSpec` and `RSpec`...

If so (Made it Level 4 (####) by accident), I'll change it to Level 3 and force push the new changes.
+Adding all the necessary changes to the Commit Message Body, and the PR Message as well.

**Review by elia — APPROVED** [review]

**Comment by elia** [comment]
> If so (Made it Level 4 (####) by accident), I'll change it to Level 3 and force push the new changes.
> +Adding all the necessary changes to the Commit Message Body, and the PR Message as well.

I think it could have been intentional, giving less relevance to the guard-file section than the mspec section, but if it looks odd to you (as a fresh readme reader) I'd be happy to change it. After all this should favor newcomers!

**Comment by og-mrk** [comment]
If the new changes, which I've amended/force-pushed, are not good enough/not welcomed, Please provide why so we could understand the "problem" at hand in `README.md` and come up with a good solution.
I'll try and reply as soon as I could 👍

**Comment by hmdne** [comment]
Thanks! Let's merge it :D

**Comment by og-mrk** [comment]
Glad I could help 🤍

**Pull request merged**
