### PR TITLE
Clarify trade-off in calling JS, see #1019

### PR DESCRIPTION
**Pull request by ashes999**
- Added "wrapping javascript libraries" section with three options discussed in #1019, along with trade-offs.

### CODE REVIEW

**Comment by ashes999** [comment]
Code review please @elia

**Comment by meh** [comment]
There's also another option, using the `.JS.` magic.

**Comment by ashes999** [comment]
@meh I can include it in my change, if you can point me to an existing document that mentions/explains how to use it, and if you can articulate the trade-off (relative to the other three options mentioned).

Otherwise, I don't have enough experience with it to comment on it :)

**Comment by meh** [comment]
I don't know where they're documented, the trade-off is they act like backticks, so they deal with native values without wrapping, while `Native` does automagical wrapping of native things when calling.

It's like `$document.JS.alert("whatever")` instead of ``` `document.alert("whatever")` ```.

**Comment by elia** [comment]
There's https://github.com/opal/opalrb.org/pull/22 which I need to merge and port to `docs/`

Will review in a few hours (on the way to home)

**Comment by Ajedi32** [comment]
Yeah, as far as I know, `.JS` is just syntactic sugar for backticks that you can use in a limited subset of circumstances.

**Pull request closed without merging**
