### PR TITLE
Allow undef to take in multiple methods at the same time

### PR DESCRIPTION
**Pull request by wied03**
Rubyspecs for this are in https://github.com/ruby/rubyspec/pull/145

### CODE REVIEW

**Comment by meh** [comment]
I'd rather `Opal.udef` worked on one method at a time but `undef_method` expanded to multiple calls to `Opal.udef`.

**Comment by meh** [comment]
Also does the same apply to `remove_method`?

**Comment by wied03** [comment]
1) I can change this to put Opal.udef in the JS once for each call if that's what you'd prefer.
2) Yes remove_method does let you supply multiple methods in MRI.

**Comment by wied03** [comment]
Rebased, pulled in the latest rubyspecs since https://github.com/ruby/rubyspec/pull/145 was merged

**Comment by meh** [comment]
1) Yeah, I'd rather keep `Opal.udef` simple.
2) Could you do the same for `remove_method` then while you're there?

**Comment by wied03** [comment]
@meh - Made those changes. It seemed like it was wrong to change the parser for undef to be like an arglist (since this is really a 'how do we represent this in JS' issue more than AST/Ruby issue). Therefore, in order to keep the return from messing things up when an undef is at the end, I wrapped multiple undefs in a function/closure.

Remove_method and undef_method already work properly w/ multiple args in Opal but I submitted another Rubyspec PR (https://github.com/ruby/rubyspec/pull/147/) to make sure it's tested.

**Comment by meh** [comment]
Sounds good.

I only have a nit, the code there seems a little overcomplicated, basically `compile_udefs` is more complicated split out than inlined since you're passing whether or not there are more than one and you already know that because you're checking it in the caller.

**Comment by wied03** [comment]
@meh - put a commit in w/ a lambda instead. These things can be made more concise but then I think it starts to be less obvious what is going on

**Comment by meh** [comment]
It's still overcomplicated for no reason, I was talking about making it this.

```ruby
def compile
  push "(function() {"

  if children.length > 1
    indent do
      children.each {|c|
        line "Opal.udef(self, '$#{c[0].to_s}');"
      }
    end
  else
    push "Opal.udef(self, '$#{children[0][0].to_s}');"
  end

  line "})();"
end
```

It's much simpler to see what is going on this way.

**Comment by wied03** [comment]
I understand. The main difference between what I have and what you just posted is that my code only puts the closure in there if there is more than 1 (trying to cut down verbosity). If that's not important, then your version is fine.

**Comment by wied03** [comment]
The cleanest way I guess is to remove the closure/function and keep the
compiler from putting a return until the last undef call but I didn't know
how to do that without modifying the parser as I mentioned before. Is there
another way to do that within the node?

sent from my mobile device

**Comment by meh** [comment]
Then move the closure inside the branch that needs it, which makes it clear why it's needed.

**Comment by wied03** [comment]
Can this be done without the closure?

sent from my mobile device

**Comment by wied03** [comment]
@meh - I see what you're saying. I was trying too hard to not duplictate the "udef" string. I incorporated your feedback here. It still might be nice to not have to have that closure if the return issue above can be dealt with.

**Comment by wied03** [comment]
I'm going to take 1 more look in the next hour to see if this can be done without the closure

**Comment by meh** [comment]
Sorry didn't see the notifications, I'm not entirely sure why the closure is required.

**Comment by wied03** [comment]
I was only using it to prevent this from happening:
```js
return Opal.udef(self, '$a');Opal.udef(self, '$b');
```

**Comment by elia** [comment]
@wied03 if possible this PR should make `undef` work with dynamic symbols too, eg.:

```rb
a = 'foo'
undef :"#{a}_bar"
```

**Comment by wied03** [comment]
1. Re: dynamic symbols, can we crawl before we walk here? This PR is already taking quite a bit of time.
2. I've done a lot of work here trying to split this out into multiple Opal.udef calls. It seems like a lot of unnecessary parser/compiler complexity just to avoid refactoring Opal.udef to accept an array as a parameter. Is this really necessary?

**Comment by meh** [comment]
@wied03 I'd rather keep the runtime as simple as possible, it's already a complexity nightmare.

On the other hand the compiler will only get worse with time, so I'd rather make the compiler slightly worse than the runtime.

**Comment by elia** [comment]
1. @wied03 that's why I started with "if possible", for me this is good for a merge but needed to note the info that dynamic symbol support is still to be added and this PR seems the best place.
2. Not sure about it being necessary but I completely agree that's better

:smile:

**Comment by wied03** [comment]
@elia - Understand if you want to capture that. Might an issue be a good place?

Made the changes. Now this:
```ruby
class T
  undef foo
end

class B
  undef foo, bar
  alias a b
end

class C
  undef foo, bar, ssss
end

class C
  undef foo, bar, ssss
  alias a b
end
```

compiles to this:
```js
/* Generated by Opal 0.9.0.dev */
(function(Opal) {
  Opal.dynamic_require_severity = "error";
  var OPAL_CONFIG = { method_missing: true, arity_check: false, freezing: true, tainting: true };
  var self = Opal.top, $scope = Opal, nil = Opal.nil, $breaker = Opal.breaker, $slice = Opal.slice, $klass = Opal.klass;

  (function($base, $super) {
    function $T(){};
    var self = $T = $klass($base, $super, 'T', $T);

    var def = self.$$proto, $scope = self.$$scope;

    
    return Opal.udef(self, '$foo');
  })($scope.base, null);
  (function($base, $super) {
    function $B(){};
    var self = $B = $klass($base, $super, 'B', $B);

    var def = self.$$proto, $scope = self.$$scope;

    
    Opal.udef(self, '$foo');
    Opal.udef(self, '$bar');;

    return Opal.alias(self, 'a', 'b');
  })($scope.base, null);
  (function($base, $super) {
    function $C(){};
    var self = $C = $klass($base, $super, 'C', $C);

    var def = self.$$proto, $scope = self.$$scope;

    
    Opal.udef(self, '$foo');
    Opal.udef(self, '$bar');
    return Opal.udef(self, '$ssss');
  })($scope.base, null);
  return (function($base, $super) {
    function $C(){};
    var self = $C = $klass($base, $super, 'C', $C);

    var def = self.$$proto, $scope = self.$$scope;

    
    Opal.udef(self, '$foo');
    Opal.udef(self, '$bar');
    Opal.udef(self, '$ssss');;

    return Opal.alias(self, 'a', 'b');
  })($scope.base, null);
})(Opal);

/* Generated by Opal 0.9.0.dev */
(function(Opal) {
  Opal.dynamic_require_severity = "error";
  var OPAL_CONFIG = { method_missing: true, arity_check: false, freezing: true, tainting: true };
  var self = Opal.top, $scope = Opal, nil = Opal.nil, $breaker = Opal.breaker, $slice = Opal.slice;

  Opal.add_stubs(['$exit']);
  return $scope.get('Kernel').$exit()
})(Opal);

```

**Comment by meh** [comment]
Looks good to me.

**Comment by meh** [comment]
Actually, I think we don't need a new token at all, there should already be an `:undef` node check there, you just have to verify the children are one or more, and dispatch to the proper compilation avoiding the `returns(..)`.

**Comment by wied03** [comment]
I didn't exactly define a new token. I just passed through the undeflist concept, which the parser already knows about, into the compiler/node code.

**Comment by meh** [comment]
Thing is, we already have the `:undef` node, and we're already able to know if it has one or more children, so it's simpler to just check that.

**Comment by wied03** [comment]
done.

**Pull request merged**
