### PR TITLE
fix String.encoding for "use strict"

### PR DESCRIPTION
**Pull request by janbiedermann**
ES5/"use strict"; make properties of primitives read only, assigning to encoding fails with a TypeError, assignment to read only property.

This patch works around this restriction by using a simple proxy object for encoding.

### CODE REVIEW

**Comment by janbiedermann** [comment]
ES6 modules use "use strict" by default.

**Comment by janbiedermann** [comment]
So this doesn't work for now, as the encoding is not set on the instance, but on the prototype instead.
Silly.

**Comment by janbiedermann** [comment]
New fix is to just comment the assignment. Tests pass, though force_encoding now is mostly useless.

**Comment by Mogztter** [comment]
@janbiedermann What about:

```js
var result = new String(self.toString())
Object.defineProperty(result, 'encoding', {
  value: encoding,
  writable: true
})
return result
```

**Comment by janbiedermann** [comment]
superseded by PR#1970

**Pull request closed without merging**
