### PR TITLE
Fix Time#yday

### PR DESCRIPTION
**Pull request by elia**
overrides and closes #636

### CODE REVIEW

**Comment by iliabylich** [comment]
MSpec has a [utility helper](https://github.com/rubyspec/mspec/blob/a67d653fce45919d28a98da3574b0a569db084de/lib/mspec/helpers/datetime.rb#L29) `with_timezone` that internally changes timezone using `ENV['TZ']`. But it seems that node doesn't refresh it internally. Switching `ENV['TZ']` in runtime doesn't change anything at all :smile: . As a result, it uses system timezone (in this case, `Pacific/Fiji`) - check this [gist](https://gist.github.com/iliabylich/5752e2e1861d002e22d6), it really returns 118. @elia any thoughts? Can we change timezone to UTC in travis.yml? Or it should be fixed on rubyspecs' side?

**Comment by elia** [comment]
@iliabylich the TZ entry in travis was added on purpose to ensure the rubyspec runs properly on time zones distant from UTC as there was a time in which we had random failures due to DST and all that :rainbow: fantastic stuff. If we could make node pick up timezones that would be great (but we still need a way to deal with TZs in phantoms), otherwise we can filter out that spec and add something custom in spec/opal.

**Comment by vais** [comment]
@iliabylich hope https://github.com/opal/opal/pull/967#issuecomment-116166482 saves you the pain :stuck_out_tongue_winking_eye:

**Comment by iliabylich** [comment]
@vais yes, I've found it after 2 minutes of googling, that's a very sad limitation. I was thinking about adding a [node-time](https://github.com/TooTallNate/node-time) to a node.js suite, patching a default `Date` js function and patching most of the `Time` methods (again, suite-specific patches). *Probably* it solves an issue.
But then we face two other problems:
+ node-time is a native extension, so I assume we can't just put into the `node_modules` dir, everyone has to setup it manually
+ I guess phantomjs doesn't work with native node modules

So, as @elia wrote before, it's much, much easier to exclude this particular test from the suite and write own tests.

**Comment by vais** [comment]
@iliabylich I agree!

**Comment by elia** [comment]
Thanks @iliabylich for pointing out that helper, I patched it to skip (actually to "noop") the spec if the requested TZ is not the current one. And I also fixed the `#yday` implementation (thanks moment.js!).

**Pull request merged**
