### PR TITLE
Resolves #1290, generate opal-builder.js

### LINKED ISSUE #1290: Compiling Ruby code from Node.js
I want to be able to compile Ruby code with Node.js.

The documentation explain how to compile code from JavaScript (Browser) with `opal-parser.js` but I think it would be great to generate `opal-builder.js` (from https://github.com/opal/opal/blob/master/lib/opal/builder.rb).

### PR DESCRIPTION
**Pull request by Mogztter**
I made some progress toward a 100% JavaScript to compile Ruby code to JavaScript :smile: 

Remaining things to do:
- [x] Implement `Pathname.expand_path` method (used in [Hike](https://github.com/sstephenson/hike/blob/v1.2.3/lib/hike/trail.rb#L49)) #1291
- [x] Implement `Kernel.open()` method (used in [Opal.PathReader](https://github.com/opal/opal/blob/master/lib/opal/path_reader.rb#L12)) #1218
- [x] Implement  `Pathname.join` method (used in [Hike](https://github.com/sstephenson/hike/blob/v1.2.3/lib/hike/paths.rb#L23)) #1301  
- [x] Incorrect type with splat operator in HikePathFinder with Opal.paths #1331

### CODE REVIEW

**Comment by Mogztter** [comment]
With some local changes I've successfully compile Ruby to JavaScript with Node.js :tada: 

```javascript
var Opal = require('opal-npm-wrapper').Opal;
require('./opal-builder.js');
require('./pathname.js');
require('./nodejs.js');

Opal.require('nodejs');
Opal.require('opal-builder');

var builder = ((Opal.get('Opal')).$$scope.get('Builder')).$new();
var result = builder.$build(process.cwd() + '/test.rb', Opal.hash());
console.log(result.$to_s());
```
```
/* Generated by Opal 0.10.0.dev */
(function(Opal) {
  Opal.dynamic_require_severity = "error";
  var OPAL_CONFIG = { method_missing: true, arity_check: false, freezing: true, tainting: true };
  var self = Opal.top, $scope = Opal, nil = Opal.nil, $breaker = Opal.breaker, $slice = Opal.slice;

  Opal.add_stubs(['$puts']);
  return self.$puts("Hello")
})(Opal);
```

**Comment by Mogztter** [comment]
@elia I think this is ready to go!

**Comment by jgaskins** [comment]
@Mogztter Nice! Have you compared compilation time vs MRI?

**Comment by elia** [comment]
hooray!

**Comment by Mogztter** [comment]
I will do some benchmarks give you numbers

**Pull request merged**
