### PR TITLE
Implement Enumerable#each_entry.

### PR DESCRIPTION
**Pull request by iliabylich**

### CODE REVIEW

**Comment by iliabylich** [comment]
@elia @vais Any ideas why this build is broken? There are specs from Rubyspec that are not filtered in bugs/unsupported (like [this one](https://github.com/ruby/spec/blob/5ab735b888ae0130dd1f3c5b5b4f23bc88bbb5a7/core/module/prepend_spec.rb#L45)), but CI runs them. Were these specs green before or..? I didn't touch lambdas and Module stuff. What's going on? :smile:

**Comment by elia** [comment]
@iliabylich no worries, we know what the problem is:

https://github.com/ruby/mspec/commit/7a19a5997aa313fe0faf7ff6f2edba1cecb44654

in conjunction with the absence of this

https://github.com/ruby/spec/commit/25f9b873eb3f636ad10e32ed735ef0b7fb007967

I think the long term solution will be to have mspec as a submodule and update it manually instead of always fetching the latest version.

---

I'll restart the build after it's fixed. Hopefully I'll look into it tonight (+6h from now) but feel free to send a PR in the meanwhile! 😉

**Comment by vais** [comment]
@iliabylich please rebase with master and try pushing again.

**Comment by iliabylich** [comment]
Rebased. That's why I usually don't add changelog entries :smile:

**Comment by elia** [comment]
> That's why I usually don't add changelog entries

Anyone knows of a better way to handle the changelog?

**Comment by iliabylich** [comment]
Probably `.gitattributes` file with
```
CHANGELOG.md merge=union
```
may work (but I'm not 100% sure). You can read [here](http://krlmlr.github.io/using-gitattributes-to-avoid-merge-conflicts/) about it.

**Comment by vais** [comment]
@elia https://about.gitlab.com/2015/02/10/gitlab-reduced-merge-conflicts-by-90-percent-with-changelog-placeholders/
LOL

**Pull request merged**
