### PR TITLE
Fix block after hash compilation/parser issue

### PR DESCRIPTION
**Pull request by wied03**
My first foray into the parser world, fixes https://github.com/opal/opal/issues/1131

Rubyspecs that probably cover this are noted in the issue, but since we can't run those yet, addressed it in the parser specs

### CODE REVIEW

**Comment by elia** [comment]
@wied03 can you rebase on master and add a test with the actual call (in `spec/opal/core/language/block_spec.rb`)? 

(If you need any help or can't do it for some reason let me know and I'll do it myself)

**Comment by wied03** [comment]
@elia - done

**Comment by elia** [comment]
@wied03 great! I'll merge just after the green :vertical_traffic_light: from travis

_(just a note on commit messages for the next PRs: would be good to avoid the leading `*` and more or less follow the [general rules](http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html) on how to format them)_

**Comment by elia** [comment]
Thanks!

**Pull request merged**
