### PR TITLE
Struct Hash Fixes

### PR DESCRIPTION
**Pull request by wied03**
…ime.js so that Number#hash can stay how it is and not make a Ruby method call)

* Change kernel to hash the name, class ID, and object ID using the string hash method
* Since string's hash is not itself anymore, changed pathname to hash its path and keep its specs passing
* Rather than returning a string here, hash the overall result to be consistent with other changes
* Fix struct hash method

### CODE REVIEW

**Comment by meh** [comment]
I'm not entirely sure I'm fine with this. Performance is going to suffer for no really really really good reason.

**Comment by wied03** [comment]
@elia - Build should now pass except some node stuff which broke on master before this PR
@meh - Which part concerns you most re: performance, the struct changes or the kernel/string/number changes?

**Comment by wied03** [comment]
@meh - I ask because the struct behavior is what's more important (to me) and it can be fixed without the other changes. As is, structs break easily in Hash'es.

I just made the other changes to try and be consistent with MRI (and generate Fixnum hashes).

**Comment by meh** [comment]
@wied03 the `#hash` changes, the `Struct` changes are fine.

If I recall correctly we decided the discrepancy with hashing from MRI was an acceptable compromise, so I'd rather keep it as is.

**Comment by wied03** [comment]
@meh - got it, changes made

**Comment by elia** [comment]
@wied03 can you fake a push in order to restart the ci process 
(amending the commit by just adding a space to the message should do the trick)

**Comment by wied03** [comment]
@elia - Thanks, I believe Travis picked it up.

**Comment by elia** [comment]
Good, yeah, I restarted the failing test but was unsure about the merging strategy of travis :)

**Comment by elia** [comment]
Thanks! (Sorry for the delay)

**Pull request merged**
