### PR TITLE
Added support for kwsplat.

### PR DESCRIPTION
**Pull request by iliabylich**
Fixed parsing issue with mass assignment and method call.
Added rubyspec/language/method_spec.rb to the test suite.
Closes https://github.com/opal/opal/issues/1317

### CODE REVIEW

**Comment by iliabylich** [comment]
Is it a first successful run of `ruby/language/method_spec`? I've got too many broken specs, would be nice to know whether this regression is mine.

**Comment by elia** [comment]
@iliabylich can you add a changelog entry? (don't worry about conflicts, if they arise I'll merge it locally)

> Is it a first successful run of ruby/language/method_spec? I've got too many broken specs, would be nice to know whether this regression is mine.

what do you mean? (sorry, I'm failing to understand)

**Comment by iliabylich** [comment]
Added changelog entry (but I guess it's not necessary since it's already in master :smile: )

**Comment by elia** [comment]
@iliabylich reverted, redoing now just to see the "Merged" mark on the PR :)

**Pull request merged**
