### PR TITLE
Kernel#=== fully compliant with rubyspec

### PR DESCRIPTION
**Pull request by vais**

### CODE REVIEW

**Comment by elia** [comment]
keep it going! ⚡️

**Comment by vais** [comment]
I'm running out of steam, it's time for dinner now :) BTW, do you know what's the deal with [module_eval only taking a block and no arguments](https://github.com/opal/opal/blob/master/opal/corelib/module.rb#L406)? Is that something Opal-specific and on purpose? (as opposed to the official docs [stating that it takes a string or a block](http://ruby-doc.org/core-2.0.0/Module.html#method-i-module_eval)). I am getting a bunch of related errors trying to get `Kernel#String` to work. Before I jump in from the deep end and try to "fix" `Module#module_eval`, thought I'd ask first.

**Comment by elia** [comment]
It's 2 things 

- Eval-ing with strings needs Opal-parser to parse the string as you probably already know
- then there's the fact that normal jus eval only evaluates in the context of the global object and iirc it's not possible to circumvent this limitation 

As usual I'd be happy to be proven wrong :D

**Comment by elia** [comment]
Here's the only eval implementation that accepts a string

https://github.com/opal/opal/blob/master/stdlib/opal-parser.rb

**Comment by vais** [comment]
Thanks, @elia. The problem I ran into is some of the rubyspecs lean heavily on meta-programming, e.g. Kernel#String specs :weary:

**Comment by elia** [comment]
https://github.com/opal/opal/issues/480

**Comment by vais** [comment]
@elia meta-programming on top of Opal == :sweat_smile::gun: moving on...

**Pull request merged**
