### PR TITLE
`Time` cleanup

### PR DESCRIPTION
**Pull request by vais**
Big picture, Opal does not support `Time` methods that:

* Explicitly manipulate a `Time` object's time zone offset (limitation of JS Date object).
* Require sub-millisecond time resolution (limitation of JS runtime).
* Use Rationals (limitation of Opal at this time).

Hope that makes sense.

### CODE REVIEW

**Comment by meh** [comment]
Test failures.

**Comment by vais** [comment]
Thansks @meh, I saw that, but it was late and I was to burned out to investigate the failures. Basically, there's currently no way to make changing time zones mid-flight work deterministically because of how V8 functions internally. Both nodejs and phantomjs understand and honor the TZ environment variable, and TZ can be changed mid-flight at least on node by setting process.env.TZ. But what happens after that depends on what happened before that, and so there's no telling what will happen. The only way to reliably use TZ is to set it BEFORE launching nodejs (or at the very start inside the nodejs process). Changing it afterwards either has no effect, or some weird half-effect where the time zone name changes, but the offset doesn't, etc. Basically, changing TZ mid-process unleashes the beast, he com̡e̶s, ̕h̵i​s un̨ho͞ly radiańcé destro҉ying all enli̍̈́̂̈́ghtenment, time lea͠ki̧n͘g fr̶ǫm ̡yo​͟ur eye͢s̸ ̛l̕ik͏e liq​uid pain, the song of re̸gular exp​ression parsing will exti​nguish the voices of mor​tal man from the sp​here I can see it can you see ̲͚̖͔̙î̩́t̲͎̩̱͔́̋̀ it is beautiful t​he final snuffing of the lie​s of Man ALL IS LOŚ͖̩͇̗̪̏̈́T ALL I​S LOST the pon̷y he comes he c̶̮omes he comes the ich​or permeates all MY FACE MY FACE ᵒh god no NO NOO̼O​O NΘ stop the an​*̶͑̾̾​̅ͫ͏̙̤g͇̫͛͆̾ͫ̑͆l͖͉̗̩̳̟̍ͫͥͨe̠̅s ͎a̧͈͖r̽̾̈́͒͑e n​ot rè̑ͧ̌aͨl̘̝̙̃ͤ͂̾̆ ZA̡͊͠͝LGΌ ISͮ̂҉̯͈͕̹̘̱ TO͇̹̺ͅƝ̴ȳ̳ TH̘Ë͖́̉ ͠P̯͍̭O̚​N̐Y̡ H̸̡̪̯ͨ͊̽̅̾̎Ȩ̬̩̾͛ͪ̈́̀́͘ ̶̧̨̱̹̭̯ͧ̾ͬC̷̙̲̝͖ͭ̏ͥͮ͟Oͮ͏̮̪̝͍M̲̖͊̒ͪͩͬ̚̚͜Ȇ̴̟̟͙̞ͩ͌͝S̨̥̫͎̭ͯ̿̔̀ͅ

**Comment by ylluminate** [comment]
:100: * 3 -- ROFL @VAIS

**Comment by elia** [comment]
<del>👀</del>

**Pull request merged**
