### PR TITLE
Fixing failing RubySpec Singleton dump_spec

### PR DESCRIPTION
**Pull request by kaiwren**
Singleton#_dump returns an empty string
Singleton#_dump returns an empty string from a singleton subclass

### CODE REVIEW

**Comment by meh** [comment]
Isn't `#_dump` for marshalling?

I don't think we'll ever be able to support that.

**Comment by kaiwren** [comment]
I was wondering why this simple a spec wasn't passing. Makes sense.

I plan to work my way through the RubySpec as time permits - any suggestions on what I should pick up (or skip)?

**Comment by meh** [comment]
Honestly I think they were in the wrong filter, should have gone into unsupported.

**Comment by vais** [comment]
@kaiwren please update this PR as follows:

1. Remove `def _dump` from `singleton.rb`
2. Create `spec/filters/unsupported/marshal.rb`. File names in `spec/filters/unsupported` generally follow a theme/topic, e.g. "tainted", or "mutable_string", and any spec whose failure falls under that topic, regardless of the class the spec is targeting, gets recorded in that topic file.
3. Add the following content to `spec/filters/unsupported/marshal.rb`:
```ruby
opal_filter "Marshal" do
  fails "Singleton#_dump returns an empty string"
  fails "Singleton#_dump returns an empty string from a singleton subclass"
end
```
@meh do you agree?

**Comment by vais** [comment]
@kaiwren 
> I plan to work my way through the RubySpec as time permits - any suggestions on what I should pick up (or skip)?

I will be working my way through `String` over the next few days. Anything else in `filters/bugs` is fair game. Regarding what specs to pick up, my strategy has been to try to fix some method I regularly use, then follow that rabbit hole wherever it goes :)

**Comment by kaiwren** [comment]
@vias Will update this PR. I think I'll go after the specs in `Array` after this.

**Comment by vais** [comment]
Thank you @kaiwren, and looking forward to more PRs for the corelib!

**Comment by kaiwren** [comment]
Raised #836 to fix this

**Pull request closed without merging**
