### PR TITLE
Fix recursive array failures for various Array methods

### PR DESCRIPTION
**Pull request by vais**

### CODE REVIEW

**Comment by elia** [comment]
awesome

**Comment by meh** [comment]
:pandaface: :+1:

**Comment by vais** [comment]
Wow, that was quick! Thanks guys.

**Comment by meh** [comment]
@vais you were just lucky, I had just woken up and checking emails :P

**Comment by vais** [comment]
@meh I appreciate the vote of confidence, but I actually would like some feedback. I am still not sure what constitutes idiomatic "ruby javascript", so if I am doing something not idiomatic, I'd like to know. I realize time is short, but if you have a chance to comment on my use of ruby from js and vice versa, please do. I see a lot of different styles and approaches used in corelib.

**Comment by meh** [comment]
@vais I do review everything before merging, if I say nothing it's because it was good or the only nitpick was related to the coding style.

Also yeah, some code in the corelib is older and I hadn't had the time to go janitor mode in a while.

**Comment by vais** [comment]
@meh that's great to hear, thanks! But keep in mind that I can help you with the janitorial tasks as well - I've got a little OCD when it comes to code :) That's why if you have any nitpicks with the coding style, time permitting, do let me know.

**Pull request merged**
