### PR TITLE
Resolves #1455, Enable specs to check escaping in Regexp

### LINKED ISSUE #1455: Invalid Regexp escaping in Opal 0.10.0.beta3 with Node.js
Given the following Ruby code:

```ruby
CommentBlockRx = %r{^/{4,}$}
```

https://github.com/asciidoctor/asciidoctor/blob/v1.5.4/lib/asciidoctor.rb#L586

Here's the result:
**Opal 0.9.2**:
```javascript
Opal.cdecl($scope, 'CommentBlockRx', /^\/{4,}$/);
```

**Opal 0.10.0.beta3**:
```javascript
Opal.cdecl($scope, 'CommentBlockRx', /^/{4,}$/);
```

You can see that the second front slash is not escaped.

### PR DESCRIPTION
**Pull request by Mogztter**
Follow-up  #1456

This is (hopefully) the proof that Regexp escaping is not fully working.
With the current implementation the following specs must fail:

 * Regexp#inspect correctly escapes forward slashes /
 * Regexp#inspect escapes 2 slashes in a row properly

### CODE REVIEW

**Comment by Mogztter** [comment]
@elia As you can see both specs are failing:
https://travis-ci.org/opal/opal/jobs/140476476
https://travis-ci.org/opal/opal/jobs/140476477

I think we need #1456 to improve Regexp escaping.

**Comment by elia** [comment]
@Mogztter 👍🏼 thanks for sticking to this!

**Comment by Mogztter** [comment]
You are welcome :)
Is there something wrong in #1456 ? Will you merging it ?

**Comment by Mogztter** [comment]
Closing this issue.
The purpose was to show that Regexp escaping is not working on master branch without #1456 fix.

**Pull request closed without merging**
