### PR TITLE
Follow ruby/rubyspec for core and library specs

### PR DESCRIPTION
**Pull request by elia**
TODO

- remove old ruby-sl stuff
- update spec/ and spec/rubyspecs (file) after having stdlib specs back into main rubyspec repo
- fix new specs

@vais: any PR targeting this branch should have `ruby-rubyspec` as the base instead of `master`. When such PRs are merged they'll update this PR automatically. Of course the same is true for the `opal/rubyspec` repo. :)

### CODE REVIEW

**Comment by vais** [comment]
Sorry, @elia, I am completely and hopelessly confused :) What exactly did you do, and what are the next steps in terms of git? Here is what I got so far:

`git fetch upstream`, business as usual, then:
```
git checkout ruby-rubyspecs
M       spec/corelib
Branch ruby-rubyspecs set up to track remote branch ruby-rubyspecs from upstream.
Switched to a new branch 'ruby-rubyspecs'
```
```
git branch
  master
* ruby-rubyspecs
```
```
git status
# On branch ruby-rubyspecs
# Changes not staged for commit:
#   (use "git add <file>..." to update what will be committed)
#   (use "git checkout -- <file>..." to discard changes in working directory)
#
#       modified:   spec/corelib (new commits)
#
no changes added to commit (use "git add" and/or "git commit -a")
```
```
git diff
diff --git a/spec/corelib b/spec/corelib
index 0c3c64b..2acb9f6 160000
--- a/spec/corelib
+++ b/spec/corelib
@@ -1 +1 @@
-Subproject commit 0c3c64b3380d71806d6642d4ab3989c6c10a8d8f
+Subproject commit 2acb9f6da1f56f4e92c00b6cf9df91a2f9843b0b
```
I can't figure out what exactly did you do other than create a new branch with the submodule pointed to a different commit in the same fork of rubyspec/rubyspec? I thought the idea was to point the submodule at a new fork of ruby/rubyspec? Help! Please explain it to me like I was 5, cause that's how I feel right now :)

**Comment by elia** [comment]
Actually you made me realize this might not be the best place for the PR, as most of the changes will happen in https://github.com/opal/rubyspec/tree/ruby-rubyspec. 

What I did is to merge `ruby/rubyspec` with our own `opal/rubyspec` and push it to the branch [`ruby-rubyspec`](https://github.com/opal/rubyspec/tree/ruby-rubyspec). The plan is to keep our fork but track changes from `ruby/rubyspec` instead of `rubyspec/rubyspec`, this will allow us to have our own fixes before they get accepted into `ruby/rubyspec` and to make PR from `opal/rubyspec` to `ruby/rubyspec`.

Sorry for the load of _rubyspec_ repetitions :)

Hope this _improves_ the explanation, otherwise I'll prepare a longer one later

**Comment by vais** [comment]
@elia hmm, it's a little confusing - would it be better for opal/rubyspec to be a fork of ruby/rubyspec instead of a fork of rubyspec/rubyspec? I.e. a fork of a fork instead of a fork that tracks changes in a parallel fork?

**Comment by elia** [comment]
The fork thing displayed by github is just metadata on the project, does nothing but recognizing the project from which one hit the "fork" button initially.

What I mean by "tracking" is where I pull new code from, which I do by setting the upstream remote/branch for a local branch (which is something local in each git clone, i.e. on your machine).

Please ask me more if needed so that I know where to go in more detail.

:turtle: 
:turtle: 
:turtle: 
:turtle: 
:turtle: 
:turtle:

**Comment by vais** [comment]
Thanks, @elia, makes sense. Back to my original question, then: I have your ruby-rubyspecs branch locally on my machine, and `git diff` shows this:
```
git diff
diff --git a/spec/corelib b/spec/corelib
index 0c3c64b..2acb9f6 160000
--- a/spec/corelib
+++ b/spec/corelib
@@ -1 +1 @@
-Subproject commit 0c3c64b3380d71806d6642d4ab3989c6c10a8d8f
+Subproject commit 2acb9f6da1f56f4e92c00b6cf9df91a2f9843b0b
```
What's next? `rake`, fix bugs, send pull requests to this branch? Should I be expecting failures when running the spec suite?

**Comment by Ajedi32** [comment]
So to clarify, since both `ruby/rubyspec` and `opal/rubyspec` are forks of `ruby/rubyspec`, GitHub will let you send pull requests between them. (E.g. https://github.com/rubyspec/rubyspec/compare/master...opal:master) So no problems there.

From git's perspective, "fork" is a meaningless term. git repositories are just directed graphs, and you can pull or merge from *any* repository, regardless of whether they're "forks" of each other.

And yes, this should probably be a PR for the `opal/rubyspec` repo. The only changes to this repo will be updating the commit the rubyspec submodule points to.

**Comment by vais** [comment]
Sorry @elia, I may be missing something obvious, but I can't figure out what to do with this.

**Comment by elia** [comment]
@vais no problem, feel free to ignore it

It already does its job as a reminder that we need to integrate `ruby/rubyspec` :frog:

**Pull request closed without merging**
