### PR TITLE
String bugs cleanup, passing #strip, #rstrip, and #hex.

### PR DESCRIPTION
**Pull request by vais**

### CODE REVIEW

**Comment by vais** [comment]
@elia @meh sorry about the duplicate commits, something didn't go quite as I intended:

1. I created the branch on machine A and pushed it to GitHub
2. I fetched the branch from GitHub to machine B
3. I rebased against the latest master and fixed conflicts
4. I pushed the branch to GitHub, but it was rejected
5. I pulled the branch from GitHub, resolved conflicts, and made a merge commit
6. I pushed the branch to GitHub and it was accepted, but it looks like this now, every commit is there twice. WTF...

My git-fu is weak. Please let me know if/what/how should I do.

**Comment by elia** [comment]
When you rebase you need to force push because otherwise it'll be rejected

**Comment by vais** [comment]
Thanks @elia. You mean just add the `-f` flag, `git push -f`? Also, what should I do with this PR, can you merge it?

**Comment by elia** [comment]
if you force push on the same branch the PR will update

it's ok to force push on your own branches

and yes it's just `git push -f` :)

**Comment by adambeynon** [comment]
@vais continues with an impressive run of commits. :star2:

**Comment by vais** [comment]
Thanks @adambeynon :)

@elia but now it's too late to force-push the thing, it just tells me `Everything up-to-date` :(
Should I just close this PR and start over?

**Comment by elia** [comment]
> @vais continues with an impressive run of commits. :star2: 
kudos indeed

**Comment by elia** [comment]
do this:

```
git reset --hard 507fb9d48c8b782500d3b744c215c93ef9443055
git push -f
```

507fb9d48c8b782500d3b744c215c93ef9443055 is the commit resulting from the rebase :)

**Comment by vais** [comment]
Worked like a charm, thanks, @elia!

**Comment by Ajedi32** [comment]
@vais I found that git becomes much easier to work with once you realize what the underlying commands are actually doing to the commit graph. Allow me to explain:

> 1. I created the branch on machine A and pushed it to GitHub

So far so good. This just adds some commits to the graph.

> 2. I fetched the branch from GitHub to machine B

No problems there.

> 3. I rebased against the latest master and fixed conflicts

Okay, so when you rebase, git isn't actually *changing* any of your commits. Commits in git are immutable. What git is actually doing is building up a new set of commits on the new base, then moving your branch pointer onto that new base. So after this, you will have one set of commits on the remote based off of your old base, and a new set of commits locally which is based off of the new base.

> 4. I pushed the branch to GitHub, but it was rejected

When you push without `--force` or `-f`, git will refuse to make changes to the remote repository which rewrite history. Because updating the remote branch to your new set of commits will require deleting the commits based off of the old base, git refuses to do it.

> 5. I pulled the branch from GitHub, resolved conflicts, and made a merge commit

When you pull from GitHub here, you're fetching the old, unrebased commits and merging them into your current branch.

> 6. I pushed the branch to GitHub and it was accepted, but it looks like this now, every commit is there twice. WTF...

And that explains why there are "two copies" of each commit. One of those copies is of the unrebased changes, and one is of the new commits that were created when you rebased.

For a better understanding of how git works, I recommend you check out http://think-like-a-git.net/ It does a pretty good job of explaining the proper mental model for thinking about operations in git.

**Comment by Ajedi32** [comment]
Here's an interactive explanation I just created: http://pcottle.github.io/learnGitBranching/?NODEMO&gist_level_id=435888cb5eea4b4016b2

Learn git branching is a bit buggy btw, so if it doesn't work I recommend trying it in Chrome for best results.

**Comment by vais** [comment]
Hey, thanks a bunch, @Ajedi32, this helps!

**Pull request merged**
