### PR TITLE
Use define property for methods and props

### PR DESCRIPTION
**Pull request by iliabylich**
Closes https://github.com/opal/opal/issues/1684

This PR defines all props using `Object.defineProperty`.
It also introduces `$$methods` and `$$ancestors` props.
Both are always up-to-date in runtime (yes, `prepend` would be much easier to implement with this patch).

There's a test under `spec/opal` suite that verifies that there are no iterable props on core JS objects.
Also I guess we need a better random generator library. `seedrandom` that is currently used pollutes `Math` module.

### CODE REVIEW

**Comment by iliabylich** [comment]
Of course it **must** be squashed before merging 😄 There's too much garbage in intermediate commits.

**Comment by iliabylich** [comment]
```
$ repeat 5 time node master.js
node master.js  0.22s user 0.03s system 98% cpu 0.261 total
node master.js  0.23s user 0.03s system 98% cpu 0.265 total
node master.js  0.23s user 0.03s system 98% cpu 0.262 total
node master.js  0.23s user 0.03s system 98% cpu 0.272 total
node master.js  0.22s user 0.03s system 98% cpu 0.259 total
```

```
$ repeat 5 time node patch.js
node patch.js  0.24s user 0.04s system 97% cpu 0.285 total
node patch.js  0.24s user 0.04s system 98% cpu 0.282 total
node patch.js  0.24s user 0.04s system 98% cpu 0.284 total
node patch.js  0.24s user 0.03s system 97% cpu 0.285 total
node patch.js  0.25s user 0.03s system 97% cpu 0.287 total
```

I can also benchmark other things, just let me know.

**Comment by elia** [comment]
@iliabylich I think we should consider for a couple of minutes if ivars should be defined as non-enumerable, probably not, but it's better to be sure

PS. I'll deal with code climate tomorrow as it's having issues with the CDN 🌐 right now 🙂, it's all good anyway

**Comment by iliabylich** [comment]
@elia Fixed. Also added docs for new props. Could you take a look please?

**Comment by Mogztter** [comment]
This is awesome, thanks @iliabylich ! :tada:

**Pull request merged**
