### PR TITLE
define_method fixes for issue #850 (Method,UnboundMethod)

### PR DESCRIPTION
**Pull request by wied03**
Pass more Rubyspecs related to unbound/bound methods.

### CODE REVIEW

**Comment by vais** [comment]
Nice work, @wied03! I just [fixed a similar issue](https://github.com/opal/opal/commit/4f4ee3b9d4dc731bc73b45776b7c99f17b54a368) the other day, and now I think my solution may have a problem :sweat_smile:

The use of `:default` is a little too hacky for my taste though. I totally see where you're coming from, having looked at the spec, but I'm starting to think the "right" way to solve this would be by using `*args` in the method signature, then looking at `args.length`. I believe that's what Ruby does, which is why it's possible to have this seeming contradiction in the spec. Resolving it with what ends up being a string works, but it's a smell that we've been moving in the wrong direction implementing this type of methods.

**Comment by wied03** [comment]
Yeah, that makes sense. I'll work up something for that.

**Comment by vais** [comment]
Kewl! One final nitpick, @wied03, Ruby raises `ArgumentError: wrong number of arguments (0 for 1..2)`. Could you do the same as a guard at the top of the method? Then you can be more explicit about `args.length` expectations throughout the rest of the method (e.g. `args.length > 1` becomes `args.length == 2`).
```
[1] pry(main)> module X
[1] pry(main)*   define_method
[1] pry(main)* end
ArgumentError: wrong number of arguments (0 for 1..2)
from (pry):2:in `define_method'
```
```
[2] pry(main)> module X
[2] pry(main)*   define_method(:a, :b, :c)
[2] pry(main)* end
ArgumentError: wrong number of arguments (3 for 1..2)
from (pry):3:in `define_method'
```
Generally you want to check your error messages against MRI. This happens to be rubyspec's weak spot.

**Comment by elia** [comment]
Thanks @wied03! 

merged adding a couple of stylistic fixes, you can check them out in https://github.com/opal/opal/commit/f955e0db5ff54c9bf126c6e550c43a469362f171.
Feel free to ask if you want more info :wink:

**Pull request merged**
