### PR TITLE
Fix test on Windows

### PR DESCRIPTION
**Pull request by Mogztter**
First step to be able to run the tests suite on AppVeyor #1584

### CODE REVIEW

**Comment by Mogztter** [comment]
The build failure is `missing SAUCE_ACCESS_KEY env var`

**Comment by Mogztter** [comment]
Rebased on master

**Comment by elia** [comment]
This looks a bit odd as the content of `contents` should come from `File.read` and thus have the same line ending as the contents coming from `path_reader.read`. I'll wait until the AppVeyor build actually runs[1] and see if that error pops out…

_[1]: at this time is blocked at `bundle install` trying to install the `json` gem_

**Comment by Mogztter** [comment]
Ok, could you please give me a link to the most recent build on Appveyor ?

**Comment by elia** [comment]
> Ok, could you please give me a link to the most recent build on Appveyor ?

The PR fixing the Ruby version worked and now it fails properly on specs (because it can't find the phantomjs executable). Here's the link anyway:

https://ci.appveyor.com/project/elia/opal/build/4

**Comment by Mogztter** [comment]
Right, we could use [phantomjs-prebuilt](https://www.npmjs.com/package/phantomjs-prebuilt) npm package to install Phantomjs or create a Rake task to do it ? Which do you prefer ?

**Comment by elia** [comment]
@Mogztter I think I solved the phantomjs problem using choco (https://github.com/opal/opal/commit/8ac3ad23244f808e9dbac40eab3a58d4fbc20d3d) but the build seems to stall at some point now, any help is very appreciated of course 🙂

**Comment by elia** [comment]
Everything's working now, and #1584 it doesn't seem to happen anymore. Maybe it has been fixed by other means, or else it was related to the git crlf configuration. Anyway please close these two issues/pr unless you have any other concerns we can address.

**Comment by Mogztter** [comment]
> Everything's working now, and #1584 it doesn't seem to happen anymore. Maybe it has been fixed by other means, or else it was related to the git crlf configuration.

Yes that's possible.
Nice work by the way! I think we should also run `mspec` wdyt ?

**Comment by elia** [comment]
Now that the basics are there why not? :)

**Pull request closed without merging**
