### PR TITLE
Update hacking procedure

### PR DESCRIPTION
**Pull request by Mogztter**
* `git submodule` needs to be updated before `bundle install`
 * Rake task `mspec_rubyspec_node` doesn't exist

### CODE REVIEW

**Comment by elia** [comment]
Great thanks!

The mspec_rubyspec_node task has bee renamed to mspec_rubyspec_nodejs, can you update that?

**Comment by Mogztter** [comment]
@elia Done

**Comment by epaulet** [comment]
README also needs an update. It's out of order.

```
First, install dependencies:

    $ bundle install
    $ npm install -g jshint

The Ruby Spec Suite related repos must be cloned as git submodules:

    $ git submodule update --init
```

**Comment by Mogztter** [comment]
@epaulet I've created a new patch for this: https://github.com/opal/opal/pull/1356
@elia If you want only one pull request, I can create a dedicated branch (I did the changes from the web interface)

**Comment by elia** [comment]
@mogztter thanks! @epaulet nice catch!

**Pull request merged**
