### PR TITLE
Basic implementation of Marshal.load and Marshal.dump.

### PR DESCRIPTION
**Pull request by iliabylich**
Things that has been changed to make `Marshal` working:
+ `Array#instance_variables` doesn't return indexes
+ `Module#instance_variables` doesn't return constants
+ `String` subclasses do not return `@literal` in ivars list.

Limitations:
+ `Marshal.dump(:symbol)` - no Symbols support
+ String encoding - dumping/loading a string with custom encoding always dumps/loads utf-16 encoded string
+ Everything about String mutating - extended strings, ivars on strings and so on.
+ `Bignum`'s can't be encoded/decoded

218 examples from rubyspec are passing (`Marshal#restore` is an alias to `Marshal#load`, so probably even 300), ~50 are failing.

### CODE REVIEW

**Comment by iliabylich** [comment]
@elia I know in MRI `Marshal` is a part of corelib. What do you think about moving it to `stdlib` for Opal? Then it will not change the size of `opal/base` or `opal/mini`

**Comment by elia** [comment]
@iliabylich this what I was thinking, let me know your considerations, I was pondering whether to introduce an `opal/full` and slim down the default opal including in it the things that are useful in the browser for most of the time, that way we can both 1. keep its size in check and 2. freely implement cool stuff like marshalling without fearing for the size (it's just a `require "corelib/THING"` away for those ho need it).

Just as a note I'll add that MRuby goes even further including in its basic bundle a dumbed down version of many methods (e.g. `gsub` can't accept a block and stuff like that). I think in our case it would make the core lib more fragile, but it's still a solution to keep in mind.

cc @meh

**Comment by eregon** [comment]
FWIW, I fixed mspec upstream in https://github.com/ruby/mspec/commit/203ec67db1855bf650bda4069cce5d39eac656e8.

**Comment by iliabylich** [comment]
@eregon Thank you so much! I was going to open a PR to mspec but for some reason I thought that it will not be be accepted :smile:

**Comment by eregon** [comment]
@iliabylich @elia @vais Anything that makes `mspec` simpler is good and a welcome change!

**Comment by iliabylich** [comment]
@eregon Thanks, pulling udpates!@elia I'll try to rebase it to the latest master (if it's possible :smile:). Just a final question, are you ok with excluding marshal stuff from `opal/opal` and forcing everyine to require 'corelib/marshal' manually?

**Comment by elia** [comment]
@iliabylich I am, let's also add an `opal/full`

**Comment by iliabylich** [comment]
Done

**Comment by elia** [comment]
w00t!

**Pull request merged**
