### PR TITLE
Correct Array#&, Array#|, Array#-, Array#uniq, and Array#uniq!

### LINKED ISSUE #1001: Array#&, Array#|, Array#-, Array#uniq, and Array#uniq! are fast and... wrong
`Array#&`, `Array#|`, `Array#-`, `Array#uniq`, and `Array#uniq!` all use a JavaScript object as a poor man's hash, storing and looking up array items as **keys** in that "hash".

I've been reluctant to change this for performance reasons, but this reminds me of the saying that code can be made infinitely fast as long as you are willing to accept an incorrect result.

@elia, @meh, @adambeynon any ideas on what (if anything) should be done with these methods?

### PR DESCRIPTION
**Pull request by vais**
Fix #1001 

```
$ bundle exec rake bench:clear
...
$ git checkout master
...
$ bundle exec rake bench:opal[benchmark/bm_array_*]
...
$ git checkout array
...
$ bundle exec rake bench:opal[benchmark/bm_array_*]
...
$ bundle exec rake bench:ruby[benchmark/bm_array_*]
...
$ bundle exec rake bench:report
Benchmark                                    Opal1  Opal2  Ruby1
benchmark/bm_array_minus_numbers.rb          0.559  1.382  0.773
benchmark/bm_array_minus_objects.rb          7.182  2.543  2.228
benchmark/bm_array_minus_strings.rb          0.563  0.929  1.055
benchmark/bm_array_union_numbers.rb          1.010  2.204  1.178
benchmark/bm_array_union_objects.rb         14.399  4.510  2.555
benchmark/bm_array_union_strings.rb          1.262  1.958  1.422
benchmark/bm_array_uniq_bang_numbers.rb      0.262  0.568  0.221
benchmark/bm_array_uniq_bang_objects.rb      3.842  1.120  0.708
benchmark/bm_array_uniq_bang_strings.rb      0.268  0.444  0.533
benchmark/bm_array_uniq_numbers.rb           0.267  0.567  0.289
benchmark/bm_array_uniq_objects.rb           3.891  1.164  0.763
benchmark/bm_array_uniq_strings.rb           0.275  0.467  0.404
benchmark/bm_array_intersection_numbers.rb          1.343  0.732
benchmark/bm_array_intersection_objects.rb          2.467  3.393
benchmark/bm_array_intersection_strings.rb          0.905  1.074
```
`Opal1` column shows results for the current `master` branch. `Opal2` are the results for the `array` branch used in this PR. `Ruby1` are MRI results (ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]) provided as a baseline of sorts.

The three missing results for `Opal1` array intersection benchmarks (`Array#&`) are missing because this method is so busted on master that the benchmark did not complete after ~10 minutes (I took pity on my macbook air and re-ran the benchmarks without those three files).

### CODE REVIEW

**Comment by meh** [comment]
Looks good.

**Comment by elia** [comment]
`rake mspec_phantomjs` is passing locally, don't know why it's failing on Travis

(anyway I restarted again [the job](https://travis-ci.org/opal/opal/jobs/70745002) to see if anything changes)

**Comment by vais** [comment]
@elia can we celebrate 1005th pull request by getting upgrading to the latest version of PhantomJS? What's holding us back?

**Comment by vais** [comment]
These PhantomJS crashes have been happening completely randomly for a while now. Given enough time, this build will pass. Maybe it will pass on a different machine in Travis' cluster. This happened before and will happen again... If this is a problem with Opal, we need to know, but the first step would be to get with the program and onto the latest/supported/up-to-date version of PhantomJS, right?

**Comment by vais** [comment]
@elia aaand... voila, just like that, the build has passed, hurray! :tada: :sweat_smile:

**Comment by elia** [comment]
> @elia can we celebrate 1005th pull request by upgrading to the latest version of PhantomJS? What's holding us back?

Lol yes, definitely. The problem is the changed API, so it's just a matter of rewiring the spec runner

**Comment by vais** [comment]
@elia cool, no rush, I guess, just need to restart the built on Travis a few times when this problem happens.

So, what do you think about this PR?

**Comment by elia** [comment]
Merged, we did the _right_ thing 😉

The only thing I'd like to have is benchmark/ips style to have more clear results. But of course that's not specific of this PR.

**Comment by vais** [comment]
@elia thanks! Let's just say it's a step in the *right* direction :smile:
Because there's more coming for `Array#&` (https://github.com/ruby/rubyspec/pull/94), and there are existing failures for `Array#|`, `Array#-`, and `Array#uniq` to be fixed :sweat_smile:

**Pull request merged**
