### PR TITLE
Enable inline_operators by default

### PR DESCRIPTION
**Pull request by vais**
Pass failing rubyspecs for String and Array inheritance

### CODE REVIEW

**Comment by vais** [comment]
The important bit here is to make rubyspecs pass with inline operators enabled. As to whether or not these should be enabled by default, I am not in a position to have an opinion on the matter.

**Comment by elia** [comment]
🎉

Has already been discussed with @adambeynon and decided to enable the optimization. 

Would you mind adding an entry in the changelog for this?

**Comment by vais** [comment]
@elia that was quick! So, no discussion on whether this should actually be the default?

**Comment by ylluminate** [comment]
Looks like we have default! :+1: https://github.com/opal/opal/commit/5fca5b1c7c2b6c6e657507decb79a44ee501c044

**Comment by elia** [comment]
See previous comment ;)

**Comment by vais** [comment]
@elia I see. The changelog look pretty out-dated now. The top entry is `## edge (upcoming 0.7.2)`. Not sure how to proceed...

**Comment by ylluminate** [comment]
@vais https://github.com/opal/opal/blob/47a0ae93dc6ecb206885fba2ab1fc4d13b9f290f/CHANGELOG.md

**Comment by elia** [comment]
Ouch, i thought I pushed an update hours ago 😣

@vais just add it under edge, I'll sync it with opal@0-7-stable tomorrow morning

**Comment by elia** [comment]
I did! 😎

Well bedtime for me, see ya in 6hrs 💤

**Comment by vais** [comment]
Thanks, @elia. BTW an update: I finally got `bundle exec rake mspec_phantom` to run. Here's what I'm getting (I think it's ok, but not sure about those warnings at the bottom):
```
$ bundle exec rake mspec_phantom
Starting MSpec Runner...
[filters] Adding 43 spec files...
[shared] Adding 160 spec files...
[lexer] Adding 1 spec files...
[parser] Adding 30 spec files...
[rubyspecs] Adding 298 spec files...
Thin web server (v1.6.3 codename Protein Powder)
Maximum connections set to 1024
Listening on localhost:9999, CTRL+C to stop
...........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
Finished
4715 examples, 0 failures (time taken: 6.349999904632568)
Unsafe JavaScript attempt to access frame with URL about:blank from frame with URL file:///Users/vais/GitHub/opal/lib/mspec/opal/sprockets.js. Domains, protocols and ports must match.

Unsafe JavaScript attempt to access frame with URL about:blank from frame with URL file:///Users/vais/GitHub/opal/lib/mspec/opal/sprockets.js. Domains, protocols and ports must match.

Unsafe JavaScript attempt to access frame with URL about:blank from frame with URL file:///Users/vais/GitHub/opal/lib/mspec/opal/sprockets.js. Domains, protocols and ports must match.

Unsafe JavaScript attempt to access frame with URL about:blank from frame with URL file:///Users/vais/GitHub/opal/lib/mspec/opal/sprockets.js. Domains, protocols and ports must match.
```

**Comment by elia** [comment]
Well done. You can ignore the warnings, they come from a phantomjs bug, I fixed them in Opal-rspec tho

https://github.com/opal/opal-rspec/commit/e8b1607cce82bb282de502fa07de83acff0445d

**Comment by adambeynon** [comment]
Awesome stuff! :metal: Are we metal speedz now?

**Comment by elia** [comment]
To get real metal speed we should use dart as the compilation target… 🎯

**Comment by vais** [comment]
@elia @adambeynon thanks, guys. Is there anything else I can help with to make 8.0 happen? I.e. any other show-stoppers?

**Comment by elia** [comment]
@vais @adambeynon we should have a look at https://github.com/opal/opal/milestones/0.8 and see if there's anything we absolutely need to ship in 0.8, all the rest should go to 0.9

**Pull request merged**
