### PR TITLE
Remove unused terminals from grammar

### PR DESCRIPTION
**Pull request by alexdowad**
Clean up a bit of cruft in the grammar. If these are ever needed, they can
be added back.

### CODE REVIEW

**Comment by elia** [comment]
Thanks! Can you regenerate the grammar with 

     rake grammar 

So we can run the CI against the cleaned up code?

**Comment by alexdowad** [comment]
Just ran `rake racc` and committed the results.

It's interesting that you commit a generated file to the repo. Is that so people can work on the code without having to install the Racc gem?

**Comment by meh** [comment]
Yeah, and because it's rarely changed.

**Comment by elia** [comment]
Thanks! If you see anything that can be improved or have any suggestions I'll be glad to hear/merge.

Also would like to mention that many of the issues under the "compiler" label are at least partially related to the grammar. 

This is just in case you'd like to get more involved or have some spare time as it's not that common to meet people that knows their way through the grammar 😁

**Comment by alexdowad** [comment]
> This is just in case you'd like to get more involved or have some spare time as it's not that common to meet people that knows their way through the grammar

If there are specific problems you'd like me to look at, please just ask.

I have picked up the maintenance of Racc and am just working towards the 2.0 release. It will be very greatly improved as compared to 1.4.

**Comment by elia** [comment]
> If there are specific problems you'd like me to look at, please just ask.

I'll review them and see if there something that can make good use of your expertise :)

> I have picked up the maintenance of Racc and am just working towards the 2.0 release. It will be very greatly improved as compared to 1.4.

Great to hear! the stuff I saw skimming through the issues and PRs on racc looks promising.

**Comment by elia** [comment]
@alexdowad I cc'ed you on a couple of issues that appear to grammar related, let me know if that's ok, any help or advice you can give is highly appreciated :)

**Pull request merged**
