### PR TITLE
Second batch of generated code optimization

### PR DESCRIPTION
**Pull request by hmdne**
This continues #2356.

### CODE REVIEW

**Comment by hmdne** [comment]
We used to generate helpers for $rb_plus, $rb_minus etc. for every top. Now we generate them in corelib.js once. Duplicate functions may also not get compiled every time, I don't know.

```
Comparison of the Asciidoctor (a real-life Opal application) compile and run:
                  Compile time: 5.968 -> 5.977 (change: +0.16%)
                      Run time: 0.270 -> 0.268 (change: -0.62%)
                   Bundle size: 4784558 -> 4761597 (change: -0.48%)
          Minified bundle size: 1027822 -> 1015123 (change: -1.24%)
            Mangled & minified: 716587 -> 705656 (change: -1.53%)

**Comment by hmdne** [comment]
`$truthy('a'['$==']('b'))` is now shortened to `$eqeq('a', 'b')`. Same with `===` -> `$eqeqeq`. This is so that we can safely cherry-pick case node elimination. Somehow, despite forcing the $truthy check, the performance is better.

```
Comparison of the Asciidoctor (a real-life Opal application) compile and run:
                  Compile time: 5.982 -> 5.962 (change: -0.33%)
                      Run time: 0.270 -> 0.269 (change: -0.50%)
                   Bundle size: 4784558 -> 4759249 (change: -0.53%)
          Minified bundle size: 1027822 -> 1015230 (change: -1.23%)
            Mangled & minified: 716587 -> 704015 (change: -1.75%)
```

**Comment by hmdne** [comment]
After backporting the case node rewriter:

```
Comparison of the Asciidoctor (a real-life Opal application) compile and run:
                  Compile time: 5.967 -> 5.963 (change: -0.05%)
                      Run time: 0.269 -> 0.269 (change: -0.32%)
                   Bundle size: 4784558 -> 4768898 (change: -0.33%)
          Minified bundle size: 1027822 -> 1016536 (change: -1.10%)
            Mangled & minified: 716587 -> 702646 (change: -1.95%)

**Comment by hmdne** [comment]
Since we don't have a `case` node anymore, we can make an `if` node generate code better.

We use a special property that `$truthy($truthy(a) ? true : b)` is the same as `$truthy($truthy(a) || b)` which itself is the same as `$truthy(a) || $truthy(b)`. Similarly we do with false on the falsy side now, but true on truthy is what `case a, b` generates actually. And `$truthy((a)['$==='](b))` we convert to `$eqeqeq('a', 'b')`. So - this commit makes a lot more `$eqeqeq`s. And `$eqeqeq` may be optimized akin to how `$rb_plus` is optimized.

```
Comparison of the Asciidoctor (a real-life Opal application) compile and run:
                  Compile time: 5.962 -> 5.947 (change: -0.24%)
                      Run time: 0.269 -> 0.269 (change: -0.31%)
                   Bundle size: 4784558 -> 4765596 (change: -0.40%)
          Minified bundle size: 1027822 -> 1015690 (change: -1.18%)
            Mangled & minified: 716587 -> 702179 (change: -2.01%)
```

**Comment by hmdne** [comment]
```
 Comparison of the Asciidoctor (a real-life Opal application) compile and run:
                  Compile time: 5.999 -> 5.987 (change: -0.19%)
                      Run time: 0.271 -> 0.268 (change: -1.11%)
                   Bundle size: 4784558 -> 4766408 (change: -0.38%)
          Minified bundle size: 1027822 -> 1015882 (change: -1.16%)
            Mangled & minified: 716587 -> 702347 (change: -1.99%)
```

-1.11% in run time... certainly this test is not fully robust, but I believe it this time :D

**Comment by hmdne** [comment]
Hm. Found some interesting `if` output:

```javascript
      } else if ($truthy(($truthy(($ret_or_1 = $rb_lt(self, 0))) ? (($truthy(($ret_or_2 = $$$('Float')['$==='](other))) ? ($ret_or_2) : ($$$('Rational')['$==='](other)))) : ($ret_or_1)))) {
```

Very ugly. Unreadable. And we most certainly don't need those $ret_or_x values.

This is for:

```ruby
    elsif self < 0 && (::Float === other || ::Rational === other)
```

Maybe we can optimize for this case somehow... can we eliminate this $ret_or_1?

**Comment by hmdne** [comment]
```javascript
  } else if (($rb_lt(self, 0) && (($eqeqeq($$$('Float'), self.$other()) || ($eqeqeq($$$('Rational'), self.$other())))))) {
```

Ok. Now I am totally satisfied :D

```
Comparison of the Asciidoctor (a real-life Opal application) compile and run:
                  Compile time: 5.968 -> 5.927 (change: -0.69%)
                      Run time: 0.270 -> 0.264 (change: -1.98%)
                   Bundle size: 4784558 -> 4697937 (change: -1.81%)
          Minified bundle size: 1027822 -> 999525 (change: -2.75%)
            Mangled & minified: 716587 -> 697985 (change: -2.60%)

**Comment by hmdne** [comment]
A slight optimization for how different types of args are generated.

```
Comparison of the Asciidoctor (a real-life Opal application) compile and run:
                  Compile time: 5.987 -> 5.911 (change: -1.28%)
                      Run time: 0.269 -> 0.264 (change: -1.91%)
                   Bundle size: 4784558 -> 4668713 (change: -2.42%)
          Minified bundle size: 1027822 -> 999325 (change: -2.77%)
            Mangled & minified: 716587 -> 697884 (change: -2.61%)

**Comment by hmdne** [comment]
Also optimize calls for `!=` and `!`. There are a few test cases that need to be investigated. Also, `BasicObject#!=` isn't compiled anymore - probably mostly because we don't call it so much anymore.

```
 Comparison of the Asciidoctor (a real-life Opal application) compile and run:
                  Compile time: 6.049 -> 5.941 (change: -1.78%)
                      Run time: 0.269 -> 0.265 (change: -1.77%)
                   Bundle size: 4784558 -> 4665414 (change: -2.49%)
          Minified bundle size: 1027822 -> 998525 (change: -2.85%)
            Mangled & minified: 716587 -> 697161 (change: -2.71%)
```

This didn't improve run times as much as I anticipated though.

**Comment by hmdne** [comment]
The tests broke due to parser upgrade actually. So, let's not bother with those at the moment.

**Comment by hmdne** [comment]
Try to heavily optimize the $truthy helper while keeping compatibility. Also, optimize the $not helper. Seems like almost no gain.

``` 
Comparison of the Asciidoctor (a real-life Opal application) compile and run:
                  Compile time: 6.089 -> 5.942 (change: -2.41%)
                      Run time: 0.269 -> 0.264 (change: -1.84%)
                   Bundle size: 4784558 -> 4665609 (change: -2.49%)
          Minified bundle size: 1027822 -> 998545 (change: -2.85%)
            Mangled & minified: 716587 -> 697179 (change: -2.71%)
```

**Comment by hmdne** [comment]
Reverting the !/!= commit gave us this:

```
Comparison of the Asciidoctor (a real-life Opal application) compile and run:
                  Compile time: 6.057 -> 5.941 (change: -1.92%)
                      Run time: 0.270 -> 0.265 (change: -1.72%)
                   Bundle size: 4784558 -> 4668844 (change: -2.42%)
          Minified bundle size: 1027822 -> 999350 (change: -2.77%)
            Mangled & minified: 716587 -> 697907 (change: -2.61%)

**Comment by hmdne** [comment]
The patchset has been formatted with test problems fixed and my messages in this thread were redacted into the commit messages.

**Comment by hmdne** [comment]
The logic for the truthy test was incorrect. After correcting it:
```
 Comparison of the Asciidoctor (a real-life Opal application) compile and run:
                  Compile time: 5.948 -> 5.892 (change: -0.95%)
                      Run time: 0.269 -> 0.263 (change: -2.39%)
                   Bundle size: 4784558 -> 4665610 (change: -2.49%)
          Minified bundle size: 1027822 -> 998547 (change: -2.85%)
            Mangled & minified: 716587 -> 697181 (change: -2.71%)

**Review by elia — APPROVED** [review]
Awesome stuff! Can't wait to get 1.4 out!

**Pull request merged**
