### PR TITLE
Rubyspecs cleanup

### PR DESCRIPTION
**Pull request by vais**
This PR removes from the `spec/rubyspecs` file the exclusions (`!...`) for files that Opal was unable to parse in the past. Now that it can, these files no longer need to be excluded entirely from the spec run, and any failures arising from running the specs in these files have been added to the appropriate bug filters instead.

### CODE REVIEW

**Comment by vais** [comment]
@elia of course it's the usual suspect, phantom/sprockets, giving me a hard time here :smile: 
https://travis-ci.org/opal/opal/jobs/96421327#L227
```
phantomjs /home/travis/build/opal/opal/tasks/testing/sprockets-phantomjs.js http://localhost:9999/
SyntaxError: Cannot handle dynamic require :rubyspec/core/module/autoload_spec:111
	/home/travis/build/opal/opal/lib/opal/compiler.rb:192:in `error'
```
SyntaxError?? If that's normal, I'll go ahead and add the exclusion for `rubyspec/core/module/autoload_spec` back in, please LMK...

**Comment by elia** [comment]
@vais, I'm very disappointed, you didn't have a single word dedicated to the surpassing ok 10k specs 😝

Will look into the failing spec, I'm quite curious to find out what the actual problem is. 🤔

🚀

**Comment by elia** [comment]
s/ok/of

**Comment by vais** [comment]
@elia :tada: :smile: 

Yeah, regarding the `SyntaxError` on dynamic require, on nodejs it just gives a bunch of `WARNING`s, but on phantom it's an error. I wasn't sure if that's by design or what's going on. Thanks for looking into this!

**Comment by elia** [comment]
@vais should be fixed by 03a4909f5a0d0e8333231f007976e6007942ccfc, waiting for the CI :)

**Pull request merged**
