### PR TITLE
Resolves #1301, Implement Pathname.join and Pathname.+

### LINKED ISSUE #1301: Implement Pathname.join method
I found the following implementation in the Ruby documentation: http://ruby-doc.org/stdlib-1.9.3/libdoc/pathname/rdoc/Pathname.html#method-i-join
```
def join(*args)
  args.unshift self
  result = args.pop
  result = Pathname.new(result) unless Pathname === result
  return result if result.absolute?
  args.reverse_each {|arg|
    arg = Pathname.new(arg) unless Pathname === arg
    result = arg + result
    return result if result.absolute?
  }
  result
end
```

Is that OK ?

### PR DESCRIPTION
**Pull request by Mogztter**
As @elia said this is not very efficient... but this is working! Feel free to add inline comments to improve the implementation

### CODE REVIEW

**Comment by elia** [comment]
Merging, thanks!

@Mogztter can you investigate if there's any spec that can be enabled for Pathname?

**Comment by Mogztter** [comment]
@elia I looked at https://github.com/ruby/spec/tree/master/library/pathname but unfortunately there's no spec for `join` and `+` methods

**Comment by vais** [comment]
There's this: https://github.com/ruby/ruby/blob/trunk/test/pathname/test_pathname.rb#L246-L259 but getting it to run is another story. There's one construct in that file that Opal cannot parse, then there's the dependencies on `Dir.mktmpdir` and who knows what else from `fileutils`. Perhaps selectively copying the relevant pieces from `test_pathname.rb` into Opal specs is the way to go?

**Comment by Mogztter** [comment]
@vais Ok I will try the relevant pieces, but I can't get rid of this error when running tests on master:

```
bundle exec rake rspec mspec_opal_nodejs
```
```
The rescue keyword Fix using more than two "rescue" in sequence #1269 ERROR
NoMethodError: undefined method `<<' for nil
<<: undefined method `<<' for nil
    at null.$new (/tmp/opal-nodejs-runner-20160207-27854-16o2fif:4693:15)
    at NilClass_alloc.method_missing [as $method_missing] (/tmp/opal-nodejs-runner-20160207-27854-16o2fif:3191:54)
    at NilClass_alloc.method_missing_stub [as $<<] (/tmp/opal-nodejs-runner-20160207-27854-16o2fif:970:35)
    at Object_alloc.$a.$$p.TMP_9 (/tmp/opal-nodejs-runner-20160207-27854-16o2fif:57907:37)
    at Object_alloc.instance_eval [as $instance_eval] (/tmp/opal-nodejs-runner-20160207-27854-16o2fif:3076:24)
    at module_constructor.protect [as $protect] (/tmp/opal-nodejs-runner-20160207-27854-16o2fif:34063:78)
    at $a.$$p.TMP_19 (/tmp/opal-nodejs-runner-20160207-27854-16o2fif:33682:88)
    at Opal.yieldX (/tmp/opal-nodejs-runner-20160207-27854-16o2fif:1122:18)
    at $a.$$p.TMP_2 (/tmp/opal-nodejs-runner-20160207-27854-16o2fif:7935:25)
    at Opal.yield1 (/tmp/opal-nodejs-runner-20160207-27854-16o2fif:1102:14)
```

```
$ rake --version
rake, version 10.4.2

$ bundle --version
Bundler version 1.7.6

$ ruby --version
ruby 1.9.3p551 (2014-11-13 revision 48407) [x86_64-linux]

$ gem --version
2.4.3
```

I checked on Travis (https://travis-ci.org/opal/opal/jobs/107440347) but I didn't find any "big" differences. Any idea ?

**Comment by vais** [comment]
@Mogztter I think this may be related to mspec having become a git submodule recently. Some variation of git submodule update and bundle update should fix this.

**Comment by Mogztter** [comment]
@vais I've updated submodule but same error. Removing this block of code solved this issue: https://github.com/opal/opal/blob/master/spec/opal/core/runtime/rescue_spec.rb#L49-L57
But I don't know why on my workspace `$ScratchPad` is nil :disappointed: 
I've tried to switch to a different version of Node.js but I can reproduce this issue when running under Phantom.js

**Comment by vais** [comment]
@Mogztter sorry for delayed reply, I have no idea what may be happening on your end. What I ended up doing when I ran into this problem is `git clone`-ing the repo from scratch, then `git submodule update --init`, then `bundle install`, then `bundle exec rake` and all tests passed. Hope the same works for you.

**Pull request merged**
