### PR TITLE
Optimize Class#new

### PR DESCRIPTION
**Pull request by jgaskins**
This is the result of modifying `Class#new` with one of my experiments from #1045 and rendering an intentionally large VDOM in a Clearwater app went from 303ms down to 267ms in Chrome, a time savings of 11.8% — roughly what I saw in those experiments.

After the VM invokes the JIT/optimizer (about 2-3 renders in), rendering without this patch converged on 123ms. With this patch, those same renders hit 101ms. This is 17.9% better, so subsequent renders benefit even more.

### CODE REVIEW

**Comment by meh** [comment]
I don't think this is the right way, I'm pretty sure this optimization can be done directly in the compiler.

In short, not emitting the argument for the splat in the function body.

**Comment by meh** [comment]
That is if I'm getting the optimization preventing issue correctly. Can you confirm please?

**Comment by elia** [comment]
Yes, if we manage to fix this at compiler level all splat calls will benefit.

Here's where the `slice.call` happens:
https://github.com/opal/opal/blob/master/lib/opal/nodes/def.rb#L129-L134

And here's the var list (params):
https://github.com/opal/opal/blob/master/lib/opal/nodes/def.rb#L94

**Comment by jgaskins** [comment]
I wasn't sure if it would actually benefit all calls because I only ran a few benchmarks in 2 browsers, so I figured I'd at least add a PR for code I already wrote that I know does help. :-)

**Comment by meh** [comment]
I don't think it has any practical difference, it's still just a method call.

**Comment by elia** [comment]
http://jsperf.com/opal-reassign-splat-args

I tried on the browsers I have available

**Comment by meh** [comment]
Looks good on here, I'll patch the compiler if nobody wants to take it.

**Comment by jgaskins** [comment]
@elia Nice, I added runs for Safari 9 and Chrome Canary. It's even more drastic than I thought on some browsers.

**Comment by elia** [comment]
@meh it's all yours 😁
@jgaskins cool, I tried WebKit nightly but I think it's being reported as safari 8

**Comment by vais** [comment]
@meh :+1: There is another splat issue that needs to be fixed in the compiler: https://github.com/opal/opal/issues/934 Basically, the code generated by the compiler should call `to_a` on the splat argument. Maybe while you are in there you can fix this one too :sweat_smile:

**Comment by meh** [comment]
@jgaskins can you try the benchmarks again to make sure I didn't fuck the implementation up please?

**Comment by jgaskins** [comment]
Nailed it!

**Comment by meh** [comment]
Cool, thanks for spending time profiling, we really need more of it :panda_face:

**Comment by ylluminate** [comment]
:+1:

**Comment by meh** [comment]
@jgaskins also if you can test with the latest commit as well, I had to change splat **calls** to make them actually compliant with Ruby, I'm pretty sure the helper will be optimized out, but you never know.

**Comment by jgaskins** [comment]
@meh Looks good:

```
Opal Default, no args, capture block: 27636548

Optimized JS, no args, capture block: 27814075

Opal Default, two args, no block: 28775224

Optimized JS, two args, no block: 29000361

Opal Default, two args, capture block: 26465777

Optimized JS, two args, capture block: 25358184
```

I ran it a few times. The `Opal Default` version was always a very slight bit lower for the first two pairs, which is probably due to `Opal.splat`, but the difference iss probably less than a GC pause would make.

This is really good work. :+1:

**Pull request closed without merging**
