### PR TITLE
0.8.0 changelog WIP

### PR DESCRIPTION
**Pull request by vais**

### CODE REVIEW

**Comment by vais** [comment]
@elia no idea why phantomjs keeps crashing on Travis for this PR :confused:

**Comment by elia** [comment]
@vais first thing that comes to mind is that they upgraded to phantomjs 2.0

> I don't always break the build, but when I do it, I do it with a CHANGELOG update

**Comment by elia** [comment]
@vais discard that, I checked the log and doesn't seem to be the case, maybe it's a minor update

**Comment by vais** [comment]
@elia LOL, right, of all the crazy stuff I threw at it over the last few days, it's the *CHANGELOG* that crashed it!

**Comment by vais** [comment]
@elia all's well again in the land of Travis :smile:

**Pull request merged**
