### PR TITLE
Improve block performance for even more cases

### PR DESCRIPTION
**Pull request by janbiedermann**
in runtime: alias, method_missing and top_define_method

### CODE REVIEW

**Comment by janbiedermann** [comment]
Effect in latest Firefox and latest Chrome, without vs with this patch, higher is better:
```
Benchmark                    5_opal-firefox-1-5-1 |     1_opal-firefox-1-5-1 |
bm_alias_method                        76.923 i/s |       +8.33%  83.333 i/s |
bm_alias_method_missing                12.048 i/s |      +12.17%  13.514 i/s |
bm_alias_alias_method                  34.483 i/s |      +26.09%  43.478 i/s |
bm_alias_alias                         30.303 i/s |      +37.50%  41.667 i/s |

Benchmark                     9_opal-chrome-1-5-1 |     12_opal-chrome-1-5-1 |
bm_alias_alias_method                  24.631 i/s |       +1.50%  25.000 i/s |
bm_alias_alias                         24.570 i/s |       +2.78%  25.253 i/s |
bm_alias_method_missing                 7.800 i/s |        +6.31%  8.292 i/s |
bm_alias_method                        53.191 i/s |       +8.05%  57.471 i/s |
```

Effect in Node is barely measurable

**Comment by janbiedermann** [comment]
I was wrong about node, i had a older version installed, latest Node is similar to latest Chrome:
```
Benchmark                      18_opal-node-1-5-1 |       15_opal-node-1-5-1 |
bm_alias_method                        54.612 i/s |       +1.90%  55.652 i/s | (variation)
bm_alias_alias                         23.255 i/s |       +3.88%  24.157 i/s |
bm_alias_alias_method                  22.725 i/s |       +4.54%  23.757 i/s |
bm_alias_method_missing                 7.738 i/s |       +11.00%  8.589 i/s | (way above variation)
```

**Comment by janbiedermann** [comment]
The benchmark:

```
class Test
  def test(a)
    a + a
  end

  def method_missing(a)
    a + a
  end

  alias testal test
  alias_method :testam, :test
end

instance = Test.new

100000.times do |i|
  # call method, alias or missing method with i
end
```

**Comment by janbiedermann** [comment]
with patch vs. Ruby 3.2.0:
```
Benchmark                            26_ruby-3-2-0 |       15_opal-node-1-5-1 |
bm_alias_method_missing                 85.393 i/s |       -89.94%  8.589 i/s |
bm_alias_alias_method                  159.241 i/s |      -85.08%  23.757 i/s |
bm_alias_alias                         158.215 i/s |      -84.73%  24.157 i/s |
bm_alias_method                        158.937 i/s |      -64.98%  55.652 i/s |
```

**Comment by janbiedermann** [comment]
Using the yaml benchmark format, other numbers are possible:
```
prelude: |
  class Test
    def test(a)
      a + a
    end

    def method_missing(method, a)
      a + a
    end

    alias testal test
    alias_method :testam, :test
  end

  instance = Test.new
benchmark:
  method: instance.test(1)
  alias: instance.testal(1)
  alias_method: instance.testam(1)
  method_missing: instance.testmi(1)
loop_count: 1000000
```
Node:
```
Benchmark                  43_opal-node-1-5-1 |            46_opal-node-1-5-1 |
alias                         6436000.000 i/s |       -0.56%  6400000.000 i/s | (variation)
alias_method                  6186000.000 i/s |      +12.32%  6948000.000 i/s | (clearly a improvement)
method_missing                1840000.000 i/s |      +21.96%  2244000.000 i/s |
```
Ruby vs Opal Node:
```
Benchmark                        44_ruby-3-2-0 |            46_opal-node-1-5-1 |
alias                         45611000.000 i/s |      -85.97%  6400000.000 i/s |
alias_method                  45869000.000 i/s |      -84.85%  6948000.000 i/s |
method_missing                12210000.000 i/s |      -81.62%  2244000.000 i/s |
method                        46213000.000 i/s |                               | (opal node failed to report/measure)
```

**Comment by janbiedermann** [comment]
Benchmarks run in #2461

**Review by elia — APPROVED** [review]
🚀

**Pull request merged**
