### PR TITLE
Remove symlink that caused problems on Windows

### LINKED ISSUE #1869: opal-0.11.1 can't be installed under ruby 2.5.1p57 (2018-03-29 revision 63029) [x64-mingw32]
opal-0.11.1 can't be installed under ruby-2.5.1p57:

`
While executing gem ... (Errno::EACCES)
    Permission denied @ rb_file_s_symlink - (./exe, C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/opal-0.11.1/bin)
`

### PR DESCRIPTION
**Pull request by elia**
Fixes #1869

@Adrian-Devries I've attached a built version without the symlink, can you try it and let me know if it works ok?

[opal-0.11.2.gem.zip](https://github.com/opal/opal/files/2312070/opal-0.11.2.gem.zip)

### CODE REVIEW

**Comment by Adrian-Devries** [comment]
Unfortunately, even with the version you've attached it still doesn't work:

> c:\Ruby25-x64>ruby -v
> ruby 2.5.1p57 (2018-03-29 revision 63029) [x64-mingw32]
> 
> c:\Ruby25-x64>gem -v
> 2.7.6
> 
> c:\Ruby25-x64>gem install opal
> ERROR:  While executing gem ... (Errno::EACCES)
>     Permission denied @ rb_file_s_symlink - (./exe, C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/opal-0.11.2/bin)

**Comment by elia** [comment]
I have entirely replaced the symlink, can you try this version?

[opal-0.11.2.gem.zip](https://github.com/opal/opal/files/2313833/opal-0.11.2.gem.zip)

**Comment by Adrian-Devries** [comment]
The message has changed slightly, the result is the same:

> c:\Ruby25-x64>gem install opal
ERROR:  While executing gem ... (Errno::EACCES)
    Permission denied @ rb_file_s_symlink - (lib/opal/cli_runners/node_modules/.bin/../chrome-remote-interface/bin/client.js, c:/Ruby25-x64/lib/ruby/gems/2.5.0/
gems/opal-0.11.2/lib/opal/cli_runners/node_modules/.bin/chrome-remote-interface)

**Comment by elia** [comment]
@Adrian-Devries so it now stops on another symlink, which is somewhat good news. I'll check the installed node modules and try to add the install task to the Windows CI build as per https://github.com/opal/opal/pull/1736/files

**Comment by elia** [comment]
@Adrian-Devries ok, thanks for the patience so far, here's another zip you can try, hopefully the last, 
The new gemspec excludes any symlink it encounters so it should be good now.

[opal-0.11.2.gem.zip](https://github.com/opal/opal/files/2315652/opal-0.11.2.gem.zip)

**Comment by Adrian-Devries** [comment]
Now it works:

> c:\Ruby25-x64>gem install opal
Successfully installed opal-0.11.2
Parsing documentation for opal-0.11.2
Installing ri documentation for opal-0.11.2
Done installing documentation for opal after 10 seconds
1 gem installed

Thank you!

**Comment by elia** [comment]
Great! I'll release v0.11.2 later today 👍🏼

**Comment by elia** [comment]
released! https://rubygems.org/gems/opal/versions/0.11.2

**Pull request merged**
