### PR TITLE
Fix class descendant issue

### PR DESCRIPTION
**Pull request by wied03**
https://github.com/opal/opal/issues/1077

### CODE REVIEW

**Comment by Ajedi32** [comment]
Should this be added to RubySpec? Seems to me this isn't something specific to Opal.

**Comment by wied03** [comment]
Probably. Can you find it anywhere in there before I submit a PR to rubyspec?

**Comment by Ajedi32** [comment]
@vais or @eregon would probably know better than me on that point. I'm actually not very familiar with the RubySpec internals. I just assumed it didn't have such a test since you mentioned in your commit message that you "could not find any ruby specs for this".

**Comment by eregon** [comment]
There is such a spec in https://github.com/ruby/rubyspec/blob/master/core/module/lt_spec.rb.

**Comment by eregon** [comment]
Have a look at https://github.com/opal/opal/blob/47969e5500b1a30697a5992f621dac0923ecdf11/spec/filters/bugs/module.rb, essentially one of the first lines can be removed and now passes :wink: 
I think you can run RubySpec with `SUITE=rubyspec bundle exec rake`.

**Comment by eregon** [comment]
(and part of the organization of the file structure is explained in http://ruby.github.io/rubyspec.github.io/organization/, but it should really make it to the README)

**Comment by Ajedi32** [comment]
Ah, makes sense. Yeah, given this fix it's likely some of those filters can be removed.

Now I'm curious though about `spec/opal/core`. Given that we already have RubySpec, what purpose do those specs serve? It seems likely to me that a lot of those specs duplicate things already in RubySpcec. Or are they mostly just meant for behavior specific to Opal?

**Comment by elia** [comment]
I think most of them are a fork of rubyspec with unsupported stuff removed and possibly (but I'm not sure) some Opal specific additions. E.g. in case of specs that had unsupported syntax but were still very useful.

**Comment by wied03** [comment]
@eregon - I missed that. Argh! I looked at one lt_spec file but missed that one.

**Comment by wied03** [comment]
I'll do another PR to use the Rubyspec route

**Pull request merged**
