### PR TITLE
Allow method_missing to receive operators

### LINKED ISSUE #1121: Missing method_missing stubs for optimized operators
$ opal -Oce '(1+2).abs'

```js
/* Generated by Opal 0.8.0 */
(function(Opal) {
  Opal.dynamic_require_severity = "error";
  function $rb_plus(lhs, rhs) {
    return (typeof(lhs) === 'number' && typeof(rhs) === 'number') ? lhs + rhs : lhs['$+'](rhs);
  }
  var self = Opal.top, $scope = Opal, nil = Opal.nil, $breaker = Opal.breaker, $slice = Opal.slice;

  Opal.add_stubs(['$abs']);
  return ($rb_plus(1, 2)).$abs()
})(Opal);
[…]
```

`Opal.add_stubs(['$abs']);` should have been `Opal.add_stubs(['$abs', '$+']);` instead

### LINKED ISSUE #1137: < and > via method missing
The following works in MRI, but not in opal:

```ruby
class Blue
  def method_missing(method_name, *args)
    puts "#{method_name}:#{args.inspect}"
  end
end

Blue.new < 5
```

^ should print ```<:[5]```

Thanks, keep up the good work!

### PR DESCRIPTION
**Pull request by elia**
fixes #1137
fixes #1121

closes #1136 - @wied03 noticed the PR just after I fixed the issue locally, sorry! 😓

### CODE REVIEW

**Comment by ryanstout** [comment]
thanks!

**Comment by wied03** [comment]
Do you want to incorporate the compiler specs I added? Also rubyspecs might
benefit from that spec you wrote. I could submit a PR to them if you want.

sent from my mobile device

**Comment by elia** [comment]
@wied03 sure, did this PR late in the night and overlooked a couple of things like those specs. 

I just reopened your PR, I'd like to merge both the specs and the changelog entry, ping me when you have updated it. Thanks!

**Comment by wied03** [comment]
@elia - Updated the PR

**Pull request merged**
