### PR TITLE
Replace ^ and $ with \A and \z in regular expressions

### PR DESCRIPTION
**Pull request by jeremyevans**
Unless you specifically want to match the start and end of any line
in the string, as opposed to the start and end of the string itself,
you should avoid using ^ and $.

I'm not sure if all of these changes are correct.  Maybe in some cases
where I made changes, you do want to match start/end of any line
in the string instead of the start/end of the string itself.

### CODE REVIEW

**Comment by elia** [comment]
Some of the updated files are also compiled to js (e.g. files in lib/opal/nodes) and js regexps doesn't support \A and \z. 

That's probably the reason for which the build is failing.

**Comment by jeremyevans** [comment]
That makes sense.  I'll try to figure out which regexps are getting compiled to js, and which are staying in ruby, and push another commit.

**Comment by jeremyevans** [comment]
Looks like the rspec tests are now fixed, but the mspec tasks are still failing. If I had to guess, it's because the compiler is being run under opal itself.

I think trying to hard code \A and \z instead of ^ and $ is not going to work.  We want to use \A and \z in ruby and ^ and $ in javascript.  I think I need to introduce constants that depend on RUBY_ENGINE in order to get the correct behavior when running both in ruby and javascript.  I'll send another patch that does that.

**Comment by elia** [comment]
Great job!

**Pull request merged**
