### PR TITLE
Coc tweaks - URL and ethnicity

### PR DESCRIPTION
**Pull request by shadowcat-mst**
This is the URL fix and the ethnicity addition, bundled together since I don't think either of these changes are remotely controversial.

@adambeynon @sarciszewski @jaen @webmaven thoughts if you have any, please

@adambeynon merge when ready please

### CODE REVIEW

**Comment by Ajedi32** [comment]
:+1:

**Comment by shadowcat-mst** [comment]
@Ajedi32 ah, hey, should probably have included you to - this is one of three, the other two are 961 and 962

**Comment by shadowcat-mst** [comment]
Note that I'm not referencing other tickets intentionally and instead @-ing people to pull them over here. Hopefully that'll give us a head start to get some discussing done.

**Comment by Ajedi32** [comment]
Yeah, no need to mention me explicitly; I've had Opal's repo on my watch list for well over two years now. I'll definitely notice when a new issue or PR is opened.

**Comment by webmaven** [comment]
:+1:

**Pull request merged**
