### PR TITLE
Fixed __END__ section parsing.

### PR DESCRIPTION
**Pull request by iliabylich**

### CODE REVIEW

**Comment by elia** [comment]
Just out of curiosity (since _no one uses DATA_) have you tried something like the following?

```rb
"
__END__
just a string
"

__END__
data stuff
```

**Comment by iliabylich** [comment]
Of course it doesn't work 😄. Don't merge it yet please, I have an idea how to fix it.

**Comment by elia** [comment]
@iliabylich possibly related: https://github.com/whitequark/parser/blob/7818d36672366d9cd23dd62baae65d9892410484/test/test_lexer.rb#L2363-L2372

**Comment by iliabylich** [comment]
@elia Yes, `parser` ignores a valid `__END__` section because it's not a part of the ruby code. I've found a solution (thanks to rubocop source), your example should work now.

**Pull request merged**
