### PR TITLE
Correct the utf-8 unpack implementation

### LINKED ISSUE #2189: Opal 1.x does not eval (on the client) ascii chars with val >= 0x10
Chars with ascii code in the range 0x80 - 0xFF cannot be compiled on the client.

For example:

`bundle exec opal -e 'require "opal-parser"; eval("©")'`

will fail.

Looks like the error is here: 

https://github.com/opal/opal/blob/6f71df4882f385dd0369bd6d4e5fdf1e762897d2/opal/corelib/string/unpack.rb#L49

but that should read `if (charcode < 0x80) utf.push(charcode)`

instead of `if (charcode < 0x100) utf.push(charcode)`  (extra zero)

### PR DESCRIPTION
**Pull request by hmdne**
fixes #2189 #2094 #2099

### CODE REVIEW

**Comment by hmdne** [comment]
So this broke unpack with: w, B, C, H, L, N, Q, S, U, V, b, c, h, l, s and v. It seems like the whole unpack implementation depends on this wrong assumption.

**Comment by hmdne** [comment]
OK, the reason is actually very simple. The current implementation works correctly most of the time for both the BINARY encoding and Unicode alike. This is why it's <0x100. Most of the time, but it's not correct in fact, we need to take encoding into account. I'm supplying the correct implementation below.

**Comment by hmdne** [comment]
I'll now rebase it on top of #2236 and remove some filters we were able to pass this time.

**Comment by hmdne** [comment]
The next commit goes a little bit beyond the initial scope. We moved some functions from string.rb to string/encoding.rb, as more functions are now encoding-aware and I implemented a bit more of the encoding library.

We can go 2 ways now, either we make string/encoding.rb mandatory, which I see it already kind of is, or we write some "polyfill" functions. At first I implemented those functions, but decide to not include them in a patch.

```ruby
  # If corelib/string/encoding isn't loaded, below are the methods that
  # will be "correct most of the time".

  alias b itself
  def encode(encoding); self; end
  alias force_encoding encode
  def length; `self.length`; end
  alias size length
  alias bytelength length

  def each_char(&block)
    return enum_for(:each_char) { length } unless block_given?
    %x{
      for (var i = 0, length = self.length; i < length; i++) {
        #{yield `self.charAt(i)`};
      }
    }
    self
  end

  def each_byte(&block)
    return enum_for(:each_byte) { bytelength } unless block_given?
    %x{
      for (var i = 0, length = self.length; i < length; i++) {
        #{yield `self.charCodeAt(i)`};
      }
    }
    self
  end

  # Those don't need to be repeated:
  def bytes
    @bytes ||= each_byte.to_a
    @bytes.dup
  end

  def chars(&block)
    return each_char.to_a unless block

    each_char(&block)
  end
```

**Comment by hmdne** [comment]
Oh and by the way, the main reason for those changes is that Ruby interprets "\x80" differently than "\u0080". Therefore pack and unpack may not be compatible with one another. After I finish this patch, the next one will try to allow strings in Opal like "\x80".

**Comment by hmdne** [comment]
Well... from a seemingly simple problem now we are here. This is still not perfect, but hopefully most people won't notice the encoding problems.

The filters are a mess, but I can assure you there's only 1 new filter added which is related to unsupported EUC-JP encoding.

I'll do benchmarks to ensure there's no big performance regression (String#+ looks scary...). Afterwards, I will also try to optimize the dready `unpack("U*")` call.

**Comment by hmdne** [comment]
I wrote a benchmark suite that measures Opal's performance on various fields, even since v0.8.0 (the interesting thing is that all those versions work on Ruby 3.0... I'll publish the code later on, but it's certainly not pretty). For this particular test, that in particular benchmarks ERB compilation on Opal compiled with Opal I noticed no statistically significant change on this patchset (so this tests both ERB compilation and ERB execution but just now I noticed it doesn't really use #+ too much, so let's try another, now less realistic, benchmark).

```ruby
`console.log("T:load:", +new Date)` # !@

require 'opal'

`console.log("T:iter1:", +new Date)` # @#

str = ''

200000.times do |i|
  str += i.to_s(2)
end

`console.log("T:iter2:", +new Date)` # #$

200000.times do |i|
  str += i.to_s(2)
end

`console.log("T:end:", +new Date)` # $%
```

This benchmark saw 5% slowdown (only between iter1 and end) after the #+ patch.

**Comment by hmdne** [comment]
Now, for the ERB benchmark. The bigger value the worse:

984e9718 (first commit before 6fddca88 aka v1.0.0-237-g6fddca88): 46
in the middle (after 6fddca88 was introduced): 263
826e795 (the last commit of this PR): 61

So, it's still 33% slower than originally, but overall it's 4 times faster. And the benchmark takes into account only compiling being done by Opal compiled by Opal.

**Comment by Mogztter** [comment]
> So, it's still 33% slower than originally, but overall it's 4 times faster. And the benchmark takes into account only compiling being done by Opal compiled by Opal.

Sounds good, I will compile Asciidoctor against your branch 👍🏻

**Comment by hmdne** [comment]
@Mogztter just in case, I may rebase this branch, but it's one of the most complicated branches for the Opal 1.2 process (to end on 21st of July) and may not make it. Feel free to leave any feedback :D

**Comment by Mogztter** [comment]
I can confirm that it's still slower but acceptable and that https://github.com/opal/opal/issues/2099 is fixed 🎉 
Transpiling Asciidoctor now takes 40 seconds (with the previous version it takes approximately 30 seconds).

**Comment by hmdne** [comment]
The performance structure for Opal compiler compiled by Opal looks like this for my particular example of:
```ruby
  out = Opal.compile("def xxyx(a,c,d); if 5; 6; elsif 7; 8; end; end" * 1000)
```

image

It's 6.88s spent on parsing, 924ms on rewriting, 353ms on compiling (while 106ms on flattening the resulting structure).

This is AFTER the patch I just submitted that gained me ~10% compiler optimization on MRI, but may also bring some benefits to Opal-on-Opal.

**Comment by hmdne** [comment]
(This one, I forgot to submit it before)

**Review by elia — APPROVED** [review]

**Comment by Mogztter** [comment]
Woot woot 🎉

**Pull request merged**
