### PR TITLE
Move `TOLERANCE = 0.00004` to spec/spec_helper so specs can pass in Chrome too

### PR DESCRIPTION
**Pull request by vais**

### CODE REVIEW

**Comment by elia** [comment]
can you also update the comment mentioning Chrome/V8?

**Comment by vais** [comment]
@elia why no love? Do you see any other problems with this PR? LMK...

**Comment by elia** [comment]
Sorry, i missed the update 😓

Thanks a bunch

**Comment by vais** [comment]
@elia :smile:

**Pull request merged**
