### PR TITLE
Improve Date.parse.

### PR DESCRIPTION
**Pull request by iliabylich**

### CODE REVIEW

**Comment by iliabylich** [comment]
How about splitting rules to separate files and `require`-ing what is really needed? Like
``` ruby
# for 'YYYY-MM-DD'
require 'date/formats/yyyy_mm_dd'
# (appends one more rule to some shared array of rules)
Date.parse('2016-10-10')
# => 'parsed date'
Date.parse('10-10-2016')
# => ArgumentError (because parser for this format wasn't required)
require 'date/formats/all'
# => 'require'-s all available formats
```

**Comment by vais** [comment]
@iliabylich that's a great deal of work! Looks good to me - please rebase with master and I'll merge it :wink:

**Comment by iliabylich** [comment]
@vais rebased. Seems `.gitattributes` doesn't work, getting conflicts on `Changelog.md` again and again

**Comment by vais** [comment]
@iliabylich :beers:

**Comment by elia** [comment]
:beers: !

**Pull request merged**
