### PR TITLE
Fix Method#arity and Method#parameters for methods generated using attr_reader/attr_writer.

### PR DESCRIPTION
**Pull request by iliabylich**
Closes https://github.com/opal/opal/issues/1424.

cc @wied03 @elia

### CODE REVIEW

**Comment by wied03** [comment]
@iliabylich - Why not submit these as Rubyspecs instead?

**Comment by iliabylich** [comment]
@wied03 This issue is Opal-specific. In an ideal world we would have something like
``` ruby
def attr_reader(*attrs)
  attrs.each do |attr|
    define_method attr do
      instance_variable_get("@#{attr}")
    end
  end
end
```
(`ruby/spec` has enough tests for methods defined through `define_method`)

All the tests in this PR a regressions tests for Opal, all the issues were caused by internals of Opal. I don't think that other ruby implementations may have the same bug and most probably `ruby/spec` doesn't need these tests.

cc @eregon

**Comment by iliabylich** [comment]
@wied03 These tests can be compared to something like `testing that method created through attr_reader can be binded to another object` or `testing that method created through attr_reader has correct #name`. Yes, we may have these bugs, and I'd say all of them should be placed to `spec/opal`

**Comment by wied03** [comment]
@iliabylich - How do we know for sure that other Rubies might not have the same issue at some point? I think if they demonstrate behavior that all Rubies should have (not JS bridging for example), then it might be a good reason to put them in there.

**Comment by iliabylich** [comment]
@wied03 This particular issue comes from Opal internals. `Module#attr_reader` directly invokes `Opal.def` that doesn't know anything about `$$arity/$$parameters` stuff. You are right, other rubies might have the same issue, but we don't know this for sure :smile: I'm not against putting these specs to `ruby/spec`, let's wait for @eregon 's response

**Comment by elia** [comment]
Merging in the meanwhile 👍🏼

**Comment by eregon** [comment]
@wied03 @iliabylich This would be perfectly fine for ruby/spec, attr_* are usually implemented differently than other methods for many reasons, so ensuring that Method introspection works would be a good test :smiley: 
I don't see anything Opal-specific in the specs per se. Of course most bugs are caused by bugs in implementation internals, but that makes the specs even more interesting to catch bugs or verify behavior on others implementations.
Some complicated regression tests involving 3+ methods might be difficult to translate to a spec, or they would need to be isolated to a smaller failing scenario. But in general, I'm all for having regression tests written as specs in ruby/spec. For instance, jruby+truffle does not have a separate test suite for regressions tests, it only has some additional specs for extra behavior (like integration with other languages).

**Pull request merged**
