### PR TITLE
Add JS module for nicer calling of native javascript operators and global functions

### PR DESCRIPTION
**Pull request by jeremyevans**
This adds support for calling the following javascript operators:
delete, in, instanceof, new, typeof, and void.  It also supports
calling global javascript functions via call.  call is aliased
to method_missing, so that you can do JS.globalFunction() to
call global javascript functions.

### CODE REVIEW

**Comment by elia** [comment]
Any reason Opal.global isn't ised in #call?

**Comment by jeremyevans** [comment]
@elia Probably because I didn't know to use it.  I'll push a new commit later today for that uses `Opal.global`.

Looks like the Travis failure is unrelated to this code.

**Comment by elia** [comment]
Yes, the failure was my fault 😖
But should be fixed on master

**Comment by jaredcwhite** [comment]
@jeremyevans Really big :+1: on this -- I can hardly wait to begin using it. I love the idea of avoiding backticks for various JS one-liners throughout my Opal code. :)

**Pull request merged**
