### PR TITLE
Add Matrix and E2MM modules

### PR DESCRIPTION
**Pull request by iliabylich**
Closes https://github.com/opal/opal/issues/1739

13 assertions of 252 from MRI's spec for Matrix are failing.

Unfortunately I can't find any specs for `Exception2MessageMapper` in MRI or RubySpec, but `Matrix` class heavily uses it and there's a plenty of tests for it in the `TestMatrix`

### CODE REVIEW

**Comment by iliabylich** [comment]
@elia ping

**Comment by elia** [comment]
@iliabylich approved on codeclimate ✅

**Comment by iliabylich** [comment]
Are you ok with code? Is it 👍 ?

**Comment by iliabylich** [comment]
Good catch, fixed!

**Comment by Mogztter** [comment]
Thanks again @iliabylich for your amazing work!

**Pull request merged**
