### PR TITLE
Array#product implementation fully compliant with rubyspec

### PR DESCRIPTION
**Pull request by vais**

### CODE REVIEW

**Comment by vais** [comment]
Fix for issue https://github.com/opal/opal/issues/699

**Comment by vais** [comment]
Regarding the [Pass "Array#product does not attempt to produce an unreasonable number of products"](https://github.com/vais/opal/commit/ef7294b522cad20e2e804803a32aa132743d1f1a#diff-981b14160ae83ab1ab0c0936525d462dR1161) commit: [this max number](https://github.com/vais/opal/commit/ef7294b522cad20e2e804803a32aa132743d1f1a#diff-981b14160ae83ab1ab0c0936525d462dR1161) is completely arbitrary, not sure how else to handle it. In MRI there is basically a check to see if multiplication would cause integer overflow, and if it would, then the number is considered "unreasonable", and MRI will refuse to calculate the product. There is no such thing in JS. I basically pulled a max number out of a hat. It should probably be much smaller. But it's small enough for the spec to get the `RangeError` that it's expecting, so the spec passes.

**Comment by vais** [comment]
@meh please take a moment to close [the issue](https://github.com/opal/opal/issues/699) when you get a chance.

**Comment by Ajedi32** [comment]
@vais For future reference, I'm pretty sure GitHub will close related issues automatically when the pull request gets merged if you put "Fix #issue-id" somewhere in one of your commit messages.

**Comment by vais** [comment]
@Ajedi32 oh, sweet, I didn't know that, thanks!

**Pull request merged**
