### PR TITLE
Updating Contributing.md to mention installation of jshint

### PR DESCRIPTION
**Pull request by kaiwren**

### CODE REVIEW

**Comment by vais** [comment]
Good catch, thanks, @kaiwren

**Comment by vais** [comment]
@elia do you think jshint could be vendored into stdlib/nodejs/node_modules?

**Comment by elia** [comment]
stdlib node_modules are intended to be something used by stdlib/nodejs stuff, so I think it's ok to keep it external

**Comment by vais** [comment]
Ok, thanks @elia

**Pull request merged**
