### PR TITLE
Use MRI rubyspec fork

### PR DESCRIPTION
**Pull request by vais**

### CODE REVIEW

**Comment by elia** [comment]
Awesome! 👏🏼

**Comment by elia** [comment]
@vais great stuff, next step is to send out a PR to ruby/rubyspec, you think we need to do anything before that?

**Comment by vais** [comment]
Thanks, @elia!

I still need help with a couple things related to this PR:

1) We have this in our `.gitmodules` file now:
```
[submodule "spec/corelib"]
	path = spec/corelib
	url = https://github.com/opal/rubyspec
	branch = merge-mri-fork
```
I think in our opal/rubyspec fork the `merge-mri-fork` branch should be merged with `master`, and `.gitmodules` updated here in opal/opal to point to opal/rubyspec `master` by default again.

2) `cruby_tests` Rake task is broken - as you can see in the Rakefile, I excluded it for now - couldn't figure out why `assert_nothing_raised` cannot be called inside `TestCall` anymore. Maybe with your experience you can get it working once again. It shouldn't have anything to do with rubyspec - I guess updating the test/cruby submodule to the latest commit broke this somehow.

As for contributing upstream to ruby/rubyspec, I do not believe we have anything of interest to other implementations - as you can see [here](https://github.com/ruby/rubyspec/compare/master...opal:merge-mri-fork), all of our commits have to do with making rubyspec run on Opal. Except maybe [this one](https://github.com/ruby/rubyspec/commit/39c43b469f63fef3a0c31ecda5e1b76aca8ddcd1).

I must admit all of this is still very confusing to me, so please correct me if I'm wrong :wink:

**Comment by vais** [comment]
@elia unless you feel we should get completely in sync with ruby/rubyspec fork? Maybe even make our fork of rubyspec/rubyspec for convenience become a fork of ruby/rubyspec instead?

**Comment by elia** [comment]
1) probably push -f is the way unless it's a clean fast forward 
2) Will have a look 
3) I see some value in using the "official" rubyspec and also in having Opal kinda recognized in it

As of changing the fork origin I'll check what tools github makes available. Our fork was just a mean to send official PRs initially and personally I see it as quite expendable.

**Comment by vais** [comment]
@elia I took care of item 1) above. Items 2) and 3) I'm leaving in your capable hands :smile:

**Comment by vais** [comment]
@elia one last thing, since I don't feel comfortable deleting branches that I did not create, could you please take a look: the following two branches have been abandoned and should probably be deleted: `jshint` (the first attempt at adding linting to the project) and `ruby-rubyspecs` (the first attempt at catching up with ruby/rubyspec). Both tasks have since been accomplished and are in `master`.

**Comment by elia** [comment]
Marvelous! 👐🏼

**Comment by elia** [comment]
- [x] cruby_tests
- [x] delete old branches
- [x] mri fork to opal/rubyspecs@master

**Comment by vais** [comment]
@elia :sparkles:

**Comment by ylluminate** [comment]
Good calls @elia & good work @vais.

**Pull request merged**
