### PR TITLE
Add an exception for Tokyo fractional timezone. Fixes #2405

### LINKED ISSUE #2405: Bug: `Time.new` for old date returns wrong results when `utc_offset` given
**Describe the bug**
`Time.new` returns a weird time when:

- 7th argument `utc_offset` is not nil
- System timezone is not UTC
- 1st argument `year` is around 19th century or before (this seems to depend on the timezone)

Because of this bug, DateTime tests fail on my environment.

Opal version: master (v1.4.1)

**To Reproduce**
Below is tested on a system whose timezone is `Asia/Tokyo`.
```
$ ruby -e 'p Time.new(1800, 1, 1, 0, 0, 0, 0)'
1800-01-01 00:00:00 +0000
$ opal -e 'p Time.new(1800, 1, 1, 0, 0, 0, 0)'
1799-12-31 23:59:01 UTC
```

This seems to be caused by the difference of timezone offset before and after standard time started to be used.
```
$ node
Welcome to Node.js v16.7.0.
Type ".help" for more information.
> new Date(2022, 0, 1).getTimezoneOffset()
-540
> new Date(1800, 0, 1).getTimezoneOffset()
-558
```

### PR DESCRIPTION
**Pull request by hmdne**
This fixes #2405.

I would recommend some consultation before merging this.

### CODE REVIEW

**Comment by elia** [comment]
Maybe we should consider using `Intl`, although I'm not sure exactly how it can be used it seems like it knows better WRT timezones:

```
> new Intl.DateTimeFormat('en-US', {timeZone: 'Asia/Tokyo',hour: 'numeric', minute: 'numeric', second: 'numeric',}).format(Date.UTC(1887, 11, 20, 3, 0, 0, 200))
< "12:18:59 PM"
> new Intl.DateTimeFormat('en-US', {timeZone: 'Asia/Tokyo',hour: 'numeric', minute: 'numeric', second: 'numeric',}).format(Date.UTC(1888, 11, 20, 3, 0, 0, 200))
< "12:00:00 PM"
```

**Comment by elia** [comment]
cc @takaram

**Comment by elia** [comment]
Delayed to when we'll have a more general solution, meanwhile the patch in this PR can be used to make tests pass locally.

**Comment by hmdne** [comment]
Outdated, closing

**Pull request closed without merging**
