### PR TITLE
Fix #1230 (interpolating an empty expr into string)

### LINKED ISSUE #1230: SyntaxError: Unexpected token ')'
Invalid javascript generated when trying to interpolate an empty expression `"#{}"`

http://opalrb.org/try/?code:%22%23%7B%7D%22

### PR DESCRIPTION
**Pull request by vais**
¯\_(ツ)_/¯

### CODE REVIEW

**Comment by elia** [comment]
@vais i suggest to add a regression test for this, the one in #1230 looks good enough

**Comment by elia** [comment]
aaand there's no spec proposed in #1230, sorry 😖

(I thought I saw it in one of the email notifications, will get some sleep and try again)

**Comment by vais** [comment]
@elia this definitely needs a test, just wasn't sure where to put it :blush: LMK...

**Comment by elia** [comment]
I'd say in rubyspec under "language", even if it could be argued that it can be seen as a buggish behavior…

Cc @eregon

**Comment by eregon** [comment]
Yeah, this is mostly a parser thing, so language seems right.
An empty expression like that actually evaluates to `nil`:
```ruby
[1] pry(main)> def nil.to_s; "ahah"; end
=> :to_s
[2] pry(main)ahah> "#{}"
=> "ahah"
```
Feel free to implement or not that behavior though :wink:

**Pull request merged**
