### PR TITLE
Implement Proc#curry

### LINKED ISSUE #1009: .curry on Proc and Method
I've started to use this more and more in my code.  No worries though, I'm sure you guys have better things to work on.

http://ruby-doc.org/core-1.9.3/Proc.html#method-i-curry

Thanks!

### PR DESCRIPTION
**Pull request by vais**
Fix #1009 

YO, DAWG, I HEARD YOU LIKE FUNCTIONS, SO I PUT MORE FUNCTIONS IN YOUR FUNCTIONS' FUNCTIONS

### CODE REVIEW

**Comment by ryanstout** [comment]
Nice work!

**Comment by vais** [comment]
Yo, @ryanstout I heard you like functions :stuck_out_tongue_winking_eye:

**Comment by vais** [comment]
Sorry, couldn't resist :smile:

**Comment by elia** [comment]
Curry on with the great work!

_couldnt resist either 🌝_

**Comment by vais** [comment]
Hehe, thanks, @elia

**Pull request merged**
