### PR TITLE
Builder fix and allow for .rb.erb

### PR DESCRIPTION
**Pull request by janbiedermann**
.rb.erb is required to make ruby-hyperloop work with electron-opal
ruby-hyperloop cant use .opalerb because the files are required server (matz ruby) and client side (opal ruby) the same

### CODE REVIEW

**Comment by janbiedermann** [comment]
oops, dont know why the fix multiline is still in there, tell me if it hurts and to what branch i shall provide the PR

**Comment by janbiedermann** [comment]
this needs more work

**Comment by elia** [comment]
Have you tried working on the server side to support `opalerb` as an extension? I have nothing against improving support for this things but maybe it's easier (probably depends on the cruby framework).


An additional consideration:

I'd say that we need a better API for extension/compiler support in builder, but that's also something that brings in the direction of a full blown building system like Sprockets or Webpack etc. So my hope is that we'll find the sweet spot between the two extremes 😄

**Comment by janbiedermann** [comment]
so actually thats what i am doing here https://github.com/janbiedermann/opal-webpack-loader
ruby-hyperloop eliminates .erb files, so this is no longer a issue
moving to webpack seems to provider improved options for building assets
Thats why I close this

**Pull request closed without merging**
